// Careers & Recruitment prototype contract (M28 — Phase 6 form wireframes + Phase 7 owner-dashboard wireframes).
// Pages: docs/careers/wireframes/html (generated by docs/careers/wireframes/tools/build.py), served on :4175 (playwright.config.mjs).
// Owner values below are FROZEN (M28 §06–§21, §28, §34–§46, §51, §54): the tests fail if a wireframe adds, drops or renames one.
// Titles avoid "— AR"/"— EN" on purpose so scripts/qa-matrix.mjs keeps counting only the menu pages.
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { DESKTOP_MIN } from '../../viewports.mjs';

const C = (process.env.SHELTER_CAREERS_URL || 'http://127.0.0.1:4175').replace(/\/$/, '') + '/';
const isDesk = ti => ti.project.use.viewport.width >= DESKTOP_MIN;
const onlyOn = (ti, name) => test.skip(!ti.project.name.endsWith(`-${name}`), `structure check: runs once on ${name}`);

// ---- frozen owner values
const GROUPS = ['البيانات الشخصية', 'السكن', 'المؤهل والخبرة', 'معلومات العمل', 'المرفقات', 'الإقرار'];
const FIELDS = ['name', 'phone', 'email', 'gender', 'dob', 'marital', 'nat', 'city', 'area', 'edu', 'years', 'same', 'working', 'job', 'salary', 'license', 'notes', 'files', 'consent'];
const CONSENT = 'أقر بأن جميع المعلومات المدخلة في طلب التوظيف صحيحة، وأوافق على قيام SHELTER COFFEE بجمع واستخدام بياناتي لغرض دراسة طلب التوظيف والتواصل معي بشأنه.';
const EDU = ['توجيهي ناجح', 'توجيهي راسب', 'بكالوريوس', 'ماستر', 'دكتوراه', 'على مقاعد الدراسة'];
const EXP = ['بدون خبرة', 'أقل من سنة', '1–2 سنة', '3–5 سنوات', '6–10 سنوات', 'أكثر من 10 سنوات'];
const MARITAL = ['أعزب', 'متزوج', 'أخرى'];
const STATUSES = ['تم الاستلام', 'قيد المراجعة', 'مرشح للمقابلة', 'تمت المقابلة', 'مقبول', 'مرفوض', 'مؤرشف'];
const RANGES = ['اليوم', 'آخر 7 أيام', 'آخر 30 يوم', 'هذا الشهر', 'كل الوقت'];
const COLS = ['الاسم', 'الوظيفة المتقدم لها', 'المدينة', 'سنوات الخبرة', 'الراتب المتوقع', 'تاريخ التقديم', 'حالة الطلب'];
const FILTERS = ['الاسم', 'رقم الهاتف', 'الوظيفة', 'المدينة', 'المؤهل العلمي', 'سنوات الخبرة', 'الحالة', 'الجنس', 'الجنسية', 'تاريخ التقديم'];
const LOCS = ['SHELTER COFFEE DRIVE', 'SHELTER COFFEE HOUSE'];
const FORBIDDEN = ['صورة شخصية', 'وسيلة مواصلات', 'مستوى الإنجليزية', 'اللغات', 'الفرع المفضل', 'الشفتات', 'تصريح العمل', 'معلومات صحية', 'إصابات', 'طريقة التواصل', 'LinkedIn', 'كيف عرفت', 'جهة الدراسة', 'آخر جهة عمل', 'موعد المباشرة', 'دبلوم', 'التخصص'];

const PUBLIC = ['index', 'form-a', 'form-a-errors', 'form-a-jo', 'form-a-nonjo', 'form-a-upload', 'form-a-cv-unknown', 'form-a-file-errors', 'form-a-network',
  'form-b', 'form-b-s2', 'form-b-s3', 'form-b-s4', 'form-b-errors', 'success', 'track', 'track-error', 'track-result', 'en-careers'];
const DASH = ['overview', 'list', 'list-filters', 'list-columns', 'list-bulk', 'bulk-confirm', 'quickview', 'application', 'interviews', 'archived', 'delete-confirm', 'export', 'settings'];
const UPLOAD = 'اسحب الملفات هنا أو اضغط للرفع'; // the upload control's label (المرفقات + this text)
const DESKTOP_ONLY = ['list-columns']; // column chooser applies to the desktop table; mobile uses cards

// ---- one in-page audit used by every page × viewport
async function audit(page, touch) {
  return page.evaluate(touch => {
    const vis = e => e.getClientRects().length > 0 && getComputedStyle(e).visibility !== 'hidden' && !e.closest('.vh');
    const own = e => [...e.childNodes].some(n => n.nodeType === 3 && n.textContent.trim());
    const SKIP = ['SCRIPT', 'STYLE', 'OPTION', 'OPTGROUP', 'SELECT', 'TEXTAREA', 'TITLE'];
    const texts = [...document.body.querySelectorAll('*')].filter(e => !SKIP.includes(e.tagName) && own(e) && vis(e));
    const name = e => `${e.tagName.toLowerCase()}${e.className && typeof e.className === 'string' ? '.' + e.className.split(' ')[0] : ''}: ${e.textContent.trim().slice(0, 30)}`;
    const tiny = [...new Set(texts.filter(e => parseFloat(getComputedStyle(e).fontSize) < 12).map(name))];
    const clipped = texts.filter(e => {
      const cs = getComputedStyle(e); if (e.clientWidth === 0 || ['auto', 'scroll'].includes(cs.overflowX)) return false;
      return e.scrollWidth - e.clientWidth > 1 || (e.scrollHeight - e.clientHeight > 1 && cs.overflowY !== 'visible');
    }).map(name);
    const TARGETS = 'a[href], button, select, textarea, input:not([type=radio]):not([type=checkbox]):not([type=file]):not([type=hidden]), label.tap, label.drop, [role=button]';
    const small = touch ? [...document.querySelectorAll(TARGETS)].filter(vis).filter(e => {
      const r = e.getBoundingClientRect(); return r.width < 43.5 || r.height < 43.5;
    }).map(name) : [];
    const controls = [...document.querySelectorAll('input:not([type=hidden]), select, textarea')];
    const unlabeled = controls.filter(e => {
      const l = [...(e.labels || [])].map(x => x.textContent.trim()).join('');
      const by = (e.getAttribute('aria-labelledby') || '').split(/\s+/).filter(Boolean).map(id => document.getElementById(id)?.textContent.trim() || '').join('');
      return !(l || by || (e.getAttribute('aria-label') || '').trim());
    }).map(e => e.id || e.name || e.type);
    const dialogs = [...document.querySelectorAll('[role=dialog]')].filter(vis).map(d => {
      const b = d.getBoundingClientRect(), x = d.querySelector('.x')?.getBoundingClientRect(), body = d.querySelector('.dbody');
      const foot = [...d.querySelectorAll('.dfoot .btn')].map(e => e.getBoundingClientRect());
      return {
        inside: b.top >= -1 && b.left >= -1 && b.right <= innerWidth + 1 && b.bottom <= innerHeight + 1,
        scrollable: !body || body.scrollHeight <= body.clientHeight + 1 || ['auto', 'scroll'].includes(getComputedStyle(body).overflowY),
        bodyUsable: !body || body.clientHeight >= Math.min(80, body.scrollHeight),
        close: !!x && x.top >= 0 && x.bottom <= innerHeight + 1 && x.width >= 44 && x.height >= 44,
        footer: foot.every(r => r.top >= 0 && r.bottom <= innerHeight + 1),
        labelled: !!d.getAttribute('aria-labelledby') && !!document.getElementById(d.getAttribute('aria-labelledby'))?.textContent.trim(),
      };
    });
    return { lang: document.documentElement.lang, dir: document.documentElement.dir, overflowX: document.documentElement.scrollWidth > innerWidth + 1,
      tiny, clipped, small, unlabeled, dialogs, h1: document.querySelectorAll('h1').length };
  }, touch);
}

async function contract(page, ti, file) {
  await page.goto(C + file + '.html');
  const r = await audit(page, !!ti.project.use.hasTouch);
  const en = file === 'en-careers';
  expect.soft(r.lang, 'lang').toBe(en ? 'en' : 'ar');
  expect.soft(r.dir, 'dir').toBe(en ? 'ltr' : 'rtl');
  expect.soft(r.h1, 'exactly one h1').toBe(1);
  expect.soft(r.overflowX, 'horizontal overflow').toBe(false);
  expect.soft(r.clipped, 'clipped text').toEqual([]);
  expect.soft(r.tiny, 'text < 12px').toEqual([]);
  expect.soft(r.small, 'touch targets < 44px').toEqual([]);
  expect.soft(r.unlabeled, 'controls without a label').toEqual([]);
  for (const d of r.dialogs) expect.soft(d, 'dialog fits the screen').toEqual({ inside: true, scrollable: true, bodyUsable: true, close: true, footer: true, labelled: true });
  const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).analyze();
  const blocking = axe.violations.filter(v => ['serious', 'critical'].includes(v.impact));
  if (blocking.length) await ti.attach(`axe-${file}.json`, { body: JSON.stringify(blocking, null, 2), contentType: 'application/json' });
  expect.soft(blocking.map(v => `${v.id} (${v.nodes.length}): ${v.nodes[0]?.target}`), 'axe serious/critical').toEqual([]);
  return r;
}

test.describe('careers · public pages (page × viewport)', () => {
  for (const p of PUBLIC) test(`${p} · layout, labels, axe @careers @responsive @a11y`, async ({ page }, ti) => { await contract(page, ti, p); });
});

test.describe('careers · owner dashboard (desktop ≥ 1024 · mobile below)', () => {
  for (const k of DASH) test(`${k} · layout, labels, axe, dialogs @careers @responsive @a11y`, async ({ page }, ti) => {
    test.skip(!isDesk(ti) && DESKTOP_ONLY.includes(k), 'desktop-only screen');
    const r = await contract(page, ti, `${isDesk(ti) ? 'd' : 'm'}-${k}`);
    if (/filters|confirm|quickview|columns|export/.test(k)) expect(r.dialogs.length, 'dialog present').toBe(1);
  });
});

// ---- behaviour on every viewport
const group = (page, name) => page.getByRole('group', { name, exact: true });

test.describe('careers · form behaviour', () => {
  test('error state: summary at top (role=alert) links to fields; inline errors are not colour-only @careers @a11y', async ({ page }) => {
    for (const f of ['form-a-errors', 'form-b-errors']) {
      await page.goto(C + f + '.html');
      const sum = page.locator('.esum[role=alert]');
      await expect(sum).toBeVisible();
      const links = await sum.locator('a').evaluateAll(as => as.map(a => ({ t: a.textContent.trim(), target: !!document.getElementById(a.hash.slice(1)) })));
      expect(links.length).toBeGreaterThan(0);
      expect(links.every(l => l.target && l.t)).toBe(true);
      const inline = await page.locator('.err').evaluateAll(es => es.map(e => e.textContent.trim()));
      expect(inline.length).toBe(links.length);
      expect(inline.every(t => t.startsWith('خطأ:'))).toBe(true); // text + icon + border, not colour alone
      const invalid = await page.locator('[aria-invalid=true]').evaluateAll(es => es.every(e => (e.getAttribute('aria-describedby') || '').includes('e-')));
      expect(invalid).toBe(true);
    }
  });

  test('variant A: empty submit → focused error summary listing every field @careers', async ({ page }) => {
    await page.goto(C + 'form-a.html');
    await page.getByRole('button', { name: 'إرسال الطلب' }).click();
    const sum = page.locator('.esum[role=alert]');
    await expect(sum).toBeFocused();
    await expect(sum).toBeInViewport();
    expect(await sum.locator('a').count()).toBe(FIELDS.length);
  });

  test('variant B: next on an empty step → step error summary; ≤ 4 steps with progress @careers', async ({ page }) => {
    await page.goto(C + 'form-b.html');
    await expect(page.locator('.prog-t')).toHaveText(/الخطوة 1 من 4/);
    expect(await page.locator('.step').count()).toBeLessThanOrEqual(4);
    await page.getByRole('button', { name: 'التالي' }).click();
    await expect(page.locator('.esum[role=alert]')).toBeFocused();
    await expect(page.locator('.esum[role=alert]')).toBeInViewport();
  });

  test('nationality: conditional fields appear and become required @careers', async ({ page }) => {
    await page.goto(C + 'form-a.html');
    const nid = page.getByLabel('الرقم الوطني'), natx = page.getByLabel('ما هي جنسيتك؟'), doc = page.getByLabel('رقم جواز السفر أو رقم وثيقة الهوية');
    for (const l of [nid, natx, doc]) await expect(l).toBeHidden();
    await group(page, 'الجنسية').getByLabel('أردني', { exact: true }).check();
    await expect(nid).toBeVisible(); await expect(nid).toHaveAttribute('required', '');
    await expect(natx).toBeHidden();
    await group(page, 'الجنسية').getByLabel('غير أردني', { exact: true }).check();
    await expect(nid).toBeHidden();
    for (const l of [natx, doc]) { await expect(l).toBeVisible(); await expect(l).toHaveAttribute('required', ''); }
  });

  test('getByLabel reaches every owner field in A and B @careers @a11y', async ({ page }) => {
    for (const f of ['form-a', 'form-b']) {
      await page.goto(C + f + '.html');
      for (const l of ['الاسم الكامل', 'رقم الهاتف', 'البريد الإلكتروني', 'اليوم', 'الشهر', 'السنة', 'الحالة الاجتماعية', 'المدينة', 'المنطقة',
        'المؤهل العلمي', 'سنوات الخبرة', 'الوظيفة المتقدم لها', 'الراتب المتوقع', 'ملاحظات إضافية', UPLOAD, 'الرقم الوطني']) expect(await page.getByLabel(l).count(), l).toBe(1);
      expect(await page.getByLabel('المرفقات').and(page.locator('input[type=file]')).count()).toBe(1); // the section is also named المرفقات
      expect(await page.getByLabel(CONSENT).count()).toBe(1);
      for (const g of ['الجنس', 'الجنسية', 'هل لديك خبرة سابقة في نفس المجال أو الوظيفة التي تتقدم لها؟', 'هل تعمل حاليًا؟', 'هل لديك رخصة قيادة؟', 'تاريخ الميلاد'])
        expect(await page.getByRole('group', { name: g, exact: true, includeHidden: true }).count(), g).toBe(1); // B keeps later steps hidden
    }
  });
});

// ---- structure contract (viewport-independent → once)
test.describe('careers · owner spec contract (public)', () => {
  test('form A: 6 groups, exactly the 19 owner fields in order, frozen options, required markers @careers @structure', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(C + 'form-a.html');
    expect(await page.locator('section.group > h2').allTextContents()).toEqual(GROUPS);
    const keys = await page.locator('[data-f]').evaluateAll(ws => ws.filter(w => !w.closest('.cond') && w.dataset.f !== 'cvpick').map(w => w.dataset.f));
    expect(keys).toEqual(FIELDS);
    const noMarker = await page.locator('[data-f]').evaluateAll(ws => ws.filter(w => !w.querySelector('.req')).map(w => w.dataset.f));
    expect(noMarker).toEqual([]);
    const notRequired = await page.locator('form.app input:not([type=hidden]), form.app select, form.app textarea').evaluateAll(es => es.filter(e => !e.required && e.name !== 'cvpick').map(e => e.id));
    expect(notRequired).toEqual([]);
    const textNoAuto = await page.locator('form.app input[type=text], form.app input[type=tel], form.app input[type=email], form.app textarea').evaluateAll(es => es.filter(e => e.getAttribute('dir') !== 'auto').map(e => e.id));
    expect(textNoAuto).toEqual([]);
    const opts = async id => (await page.locator(`#${id} option`).allTextContents()).filter(t => t !== 'اختر');
    expect(await opts('marital')).toEqual(MARITAL);
    expect(await opts('edu')).toEqual(EDU);
    expect(await opts('years')).toEqual(EXP);
    expect(await opts('dob-d')).toEqual(Array.from({ length: 31 }, (_, i) => String(i + 1)));
    expect(await opts('dob-m')).toHaveLength(12);
    const yrs = (await opts('dob-y')).map(Number); expect(yrs).toEqual([...yrs].sort((a, b) => b - a));
    expect(await page.locator('#city optgroup').getAttribute('label')).toContain('عيّنة — القائمة قيد التحقق');
    expect(await opts('city')).toHaveLength(3);
    for (const [g, o] of [['الجنس', ['ذكر', 'أنثى']], ['الجنسية', ['أردني', 'غير أردني']], ['هل تعمل حاليًا؟', ['نعم', 'لا']], ['هل لديك رخصة قيادة؟', ['نعم', 'لا']]])
      expect((await group(page, g).locator('label').allTextContents()).map(t => t.trim())).toEqual(o);
    await expect(page.locator('.ig .sfx')).toHaveText('د.أ');
    await expect(page.locator('label.drop')).toContainText('اسحب الملفات هنا أو اضغط للرفع');
    expect(await page.locator('input[type=file]').count()).toBe(1); // ONE upload area
    expect((await page.locator('label.consent').textContent()).replace('*', '').trim()).toBe(CONSENT);
    const body = await page.locator('main').textContent();
    expect(FORBIDDEN.filter(w => body.includes(w))).toEqual([]);
  });

  test('form B: same fields and order as A, ≤ 4 steps, progress indicator @careers @structure', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(C + 'form-b.html');
    expect(await page.locator('section.group > h2').allTextContents()).toEqual(GROUPS);
    const keys = await page.locator('[data-f]').evaluateAll(ws => ws.filter(w => !w.closest('.cond') && w.dataset.f !== 'cvpick').map(w => w.dataset.f));
    expect(keys).toEqual(FIELDS);
    expect(await page.locator('.step').count()).toBe(4);
    expect(await page.locator('.bars li').count()).toBe(4);
  });

  test('upload states: 3 files with one auto-detected CV · CV not detected · unsafe + oversized · network error keeps inputs @careers @structure', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(C + 'form-a-upload.html');
    expect(await page.locator('.files .file').count()).toBe(3);
    await expect(page.locator('.files .badge.cv')).toHaveCount(1);
    await expect(page.locator('.files .badge.cv')).toHaveText('السيرة الذاتية');
    await page.goto(C + 'form-a-cv-unknown.html');
    await expect(page.locator('.cvpick')).toBeVisible();
    await expect(page.locator('.cvpick legend')).toContainText('اختر أي ملف هو السيرة الذاتية');
    expect(await page.locator('.cvpick input[type=radio]').count()).toBe(3);
    await page.goto(C + 'form-a-file-errors.html');
    await expect(page.locator('#files-wrap [role=alert]')).toContainText('setup.exe');
    await expect(page.locator('#files-wrap [role=alert]')).toContainText('أكبر من الحد المسموح');
    await page.goto(C + 'form-a-network.html');
    await expect(page.locator('form [role=alert]').first()).toContainText('انقطع الاتصال');
    await expect(page.getByLabel('الاسم الكامل')).not.toHaveValue('');
    expect(await page.locator('.files .file').count()).toBe(3);
  });

  test('interactive upload: CV auto-detect, fallback chooser when no CV-like file @careers', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(C + 'form-a.html');
    const pdf = n => ({ name: n, mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 sample') });
    await page.getByLabel(UPLOAD).setInputFiles([pdf('Sample-CV.pdf'), pdf('certificate.pdf')]);
    await expect(page.locator('.files .badge.cv')).toHaveCount(1);
    await expect(page.locator('.cvpick')).toBeHidden();
    await page.getByLabel(UPLOAD).setInputFiles([pdf('document-01.pdf'), pdf('scan-02.pdf')]);
    await expect(page.locator('.cvpick')).toBeVisible();
    expect(await page.locator('.cvpick input[type=radio]').count()).toBe(2);
  });

  test('success · tracking · English page @careers @structure', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(C + 'success.html');
    await expect(page.locator('.appno')).toHaveText('JOB-2026-00125');
    await expect(page.locator('main')).toContainText('عيّنة');
    await expect(page.getByRole('link', { name: 'العودة إلى الموقع' })).toBeVisible();
    const sens = t => /@|07\d{8}|\*{4}|\d{10}/.test(t);
    expect(sens(await page.locator('main').textContent())).toBe(false);
    expect(page.url()).not.toContain('?');
    await page.goto(C + 'track.html');
    for (const l of ['رقم الطلب', 'رقم الهاتف']) await expect(page.getByLabel(l)).toBeVisible();
    await page.goto(C + 'track-error.html');
    await expect(page.locator('[role=alert]')).toContainText('تعذر العثور على الطلب');
    expect(await page.locator('[aria-invalid=true]').count()).toBe(0); // generic: never says which field was wrong
    await page.goto(C + 'track-result.html');
    const res = await page.locator('main .card').textContent();
    expect(res).toContain('قيد المراجعة');
    expect(sens(res)).toBe(false);
    for (const w of ['مقبول', 'مرشح للمقابلة', 'المقابلة', 'السيرة الذاتية']) expect(res).not.toContain(w);
    await page.goto(C + 'en-careers.html');
    const apply = page.getByRole('link', { name: /Apply/ });
    await expect(apply).toHaveAttribute('href', 'form-a.html');
    await expect(apply).toHaveAttribute('hreflang', 'ar');
    await apply.click();
    await expect(page.locator('html')).toHaveAttribute('lang', 'ar');
    expect(await page.locator('form.app').count()).toBe(1);
  });
});

test.describe('careers · owner spec contract (dashboard)', () => {
  for (const kind of ['d', 'm']) {
    test(`${kind === 'd' ? 'desktop' : 'mobile'}: overview, list, filters, bulk, dialogs, application @careers @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      const go = async f => page.goto(`${C}${kind}-${f}.html`);
      await go('overview');
      const kpis = page.locator('a.kpi');
      expect(await kpis.count()).toBe(8);
      expect(await kpis.evaluateAll(as => as.every(a => /-list\.html\?view=/.test(a.getAttribute('href'))))).toBe(true);
      expect(await page.locator('#range option').allTextContents()).toEqual(RANGES);
      await expect(page.locator('#range')).toHaveValue('هذا الشهر');
      expect(await page.locator('main').textContent()).not.toMatch(/[%٪]/);
      await go('list');
      expect(await page.locator('#sort option').count()).toBe(6);
      expect(await page.locator('#ps option').allTextContents()).toEqual(['25', '50', '100']);
      await expect(page.locator('#ps')).toHaveValue('50');
      await expect(page.getByLabel('بحث سريع')).toHaveAttribute('type', 'search');
      await expect(page.locator('.pager')).toContainText('السابق');
      await expect(page.locator('.pager')).toContainText('التالي');
      await expect(page.getByLabel('انتقل إلى صفحة')).toBeVisible();
      await expect(page.locator('#saved .chip').first()).toBeVisible();
      if (kind === 'd') {
        const heads = (await page.locator('.tbl thead th').allTextContents()).map(t => t.trim()).filter(t => t && t !== 'عرض سريع');
        expect(heads).toEqual(COLS);
        expect(await page.locator('.pager .pg').count()).toBeGreaterThan(2);
        expect((await page.locator('input[name=density]').evaluateAll(es => es.map(e => e.parentElement.textContent.trim())))).toEqual(['مريح', 'مضغوط']);
        expect(await page.locator('tr.unread .new').count()).toBe(5);
        const r6 = page.locator('.tbl tbody tr').nth(5); // read, still "تم الاستلام": read status ≠ application status
        await expect(r6.locator('.new')).toHaveCount(0); await expect(r6.locator('.st')).toHaveText('تم الاستلام');
      } else {
        expect(await page.locator('table').count()).toBe(0);
        expect(await page.locator('.acard').count()).toBe(20);
      }
      await go('list-filters');
      const fl = await page.locator('[role=dialog] .dbody > .f:not(.panel) > label, [role=dialog] .dbody > fieldset.f:not(.panel) > legend').allTextContents();
      expect(fl.map(t => t.trim())).toEqual(FILTERS);
      await expect(page.locator('[role=dialog]')).toContainText('حفظ الفلتر');
      await go('list-bulk');
      const bulk = page.getByRole('region', { name: 'إجراءات جماعية' });
      await expect(bulk).toContainText('تغيير الحالة'); await expect(bulk).toContainText('أرشفة');
      await expect(bulk).toContainText('تصدير'); await expect(bulk).toContainText('تنزيل المرفقات');
      expect((await bulk.locator('a, button').allTextContents()).filter(t => t.includes('حذف'))).toEqual([]);
      await go('bulk-confirm');
      await expect(page.locator('[role=dialog]')).toContainText('أنت على وشك تغيير حالة 20 طلبًا إلى قيد المراجعة.');
      await go('quickview');
      for (const t of ['الاسم', 'الوظيفة', 'المدينة', 'سنوات الخبرة', 'الراتب المتوقع', 'الحالة', 'الهاتف', 'البريد', 'المرفقات']) await expect(page.locator('[role=dialog]')).toContainText(t);
      expect(await page.locator('#qv-st option').allTextContents()).toEqual(STATUSES);
      await go('application');
      const secs = await page.locator('section.panel > h2').allTextContents();
      for (const s of ['الملخص', 'البيانات الشخصية', 'السكن', 'المؤهل والخبرة', 'معلومات العمل', 'المرفقات', 'الإقرار والموافقة', 'المقابلة', 'سجل الحالات', 'الطلبات السابقة', 'سجل التدقيق'])
        expect(secs.some(h => h.includes(s)), s).toBe(true);
      expect(secs.some(h => h.startsWith('الملاحظات الداخلية'))).toBe(true);
      expect(await page.locator('.notes li .by').count()).toBeGreaterThanOrEqual(2);
      await expect(page.locator('.masked').first()).toHaveText('********1234');
      await expect(page.getByRole('button', { name: 'إظهار' })).toBeVisible();
      await expect(page.locator('main')).toContainText('متقدم سابق — لديه 3 طلبات');
      await expect(page.locator('.badge.cv')).toHaveCount(1);
      expect((await page.locator('#iv-loc option').allTextContents()).slice(1)).toEqual(LOCS);
      expect(await page.locator('#app-st option').allTextContents()).toEqual(STATUSES);
      expect(await page.locator('input[type=range], input[type=number], [aria-label*=تقييم]').count()).toBe(0); // no interview scoring (§31)
      await go('archived');
      expect(await page.getByRole('link', { name: 'حذف نهائي' }).count()).toBe(6);
      await go('delete-confirm');
      const dlg = page.locator('[role=dialog]');
      await expect(dlg.getByRole('button', { name: 'حذف نهائي' })).toBeDisabled();
      await expect(dlg.getByLabel(/للتأكيد اكتب رقم الطلب/)).toBeVisible();
      await go('export');
      const ex = page.locator('[role=dialog]');
      for (const t of ['Excel', 'CSV', 'PDF', 'كل الطلبات', 'النتائج المفلترة', 'الطلبات المحددة']) await expect(ex).toContainText(t);
      await expect(ex.getByLabel('إظهار أرقام الهوية كاملة في هذا التصدير')).not.toBeChecked();
      await expect(ex.locator('.warn')).toContainText('تحذير');
      await go('interviews');
      for (const l of LOCS) await expect(page.locator('main')).toContainText(l);
      await go('settings');
      for (const t of [...LOCS, 'PENDING DATA VERIFICATION', 'v1', CONSENT]) await expect(page.locator('main')).toContainText(t);
      if (kind === 'd') {
        await go('list-columns');
        const rows = page.locator('[role=dialog] .colrow');
        const checked = await rows.evaluateAll(rs => rs.filter(r => r.querySelector('input').checked).map(r => r.textContent.trim()));
        expect(checked).toEqual(COLS);
        await expect(page.locator('[role=dialog]')).toContainText('استعادة الافتراضي');
        expect(await page.getByRole('button', { name: /اسحب لإعادة ترتيب/ }).count()).toBe(await rows.count());
      }
    });
  }
});

// ---- A/B measurement (owner delegated single-page vs multi-step to testing — M28 §67)
const VPS = [[360, 800], [390, 844], [430, 932]];
const pdf = n => ({ name: n, mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 sample') });
const radio = (g, o) => p => group(p, g).getByLabel(o, { exact: true });
// [B step, locator, action] — same order in A and B
const STEPS_FILL = [
  [1, p => p.getByLabel('الاسم الكامل'), l => l.fill('متقدم تجريبي')],
  [1, p => p.getByLabel('رقم الهاتف'), l => l.fill('0700000001')],
  [1, p => p.getByLabel('البريد الإلكتروني'), l => l.fill('applicant@example.com')],
  [1, radio('الجنس', 'ذكر'), l => l.check()],
  [1, p => p.getByLabel('اليوم'), l => l.selectOption('12')],
  [1, p => p.getByLabel('الشهر'), l => l.selectOption('4')],
  [1, p => p.getByLabel('السنة'), l => l.selectOption('1998')],
  [1, p => p.getByLabel('الحالة الاجتماعية'), l => l.selectOption('أعزب')],
  [1, radio('الجنسية', 'أردني'), l => l.check()],
  [1, p => p.getByLabel('الرقم الوطني'), l => l.fill('0000001234')],
  [2, p => p.getByLabel('المدينة'), l => l.selectOption({ index: 1 })],
  [2, p => p.getByLabel('المنطقة'), l => l.fill('منطقة تجريبية')],
  [2, p => p.getByLabel('المؤهل العلمي'), l => l.selectOption('بكالوريوس')],
  [2, p => p.getByLabel('سنوات الخبرة'), l => l.selectOption('3–5 سنوات')],
  [2, radio('هل لديك خبرة سابقة في نفس المجال أو الوظيفة التي تتقدم لها؟', 'نعم'), l => l.check()],
  [2, radio('هل تعمل حاليًا؟', 'لا'), l => l.check()],
  [3, p => p.getByLabel('الوظيفة المتقدم لها'), l => l.fill('باريستا')],
  [3, p => p.getByLabel('الراتب المتوقع'), l => l.fill('450')],
  [3, radio('هل لديك رخصة قيادة؟', 'نعم'), l => l.check()],
  [3, p => p.getByLabel('ملاحظات إضافية'), l => l.fill('ملاحظة تجريبية')],
  [4, p => p.locator('label.drop'), (l, p) => p.getByLabel(UPLOAD).setInputFiles([pdf('Sample-CV.pdf'), pdf('certificate.pdf'), pdf('course.pdf')])],
  [4, p => p.getByLabel(CONSENT), l => l.check()],
];

async function run(page, variant, { skip = -1 } = {}) {
  let n = 0, scrolled = 0; const stepScreens = [];
  const screens = () => page.evaluate(() => +(document.documentElement.scrollHeight / innerHeight).toFixed(2));
  const reach = async loc => { // the minimal scroll a person needs to bring the control into view (16px margin)
    const y0 = await page.evaluate(() => scrollY);
    await loc.evaluate(e => { const r = e.getBoundingClientRect(), m = 16; const dy = r.bottom > innerHeight - m ? r.bottom - (innerHeight - m) : r.top < m ? r.top - m : 0; if (dy) scrollBy(0, dy); });
    scrolled += Math.abs((await page.evaluate(() => scrollY)) - y0);
  };
  const next = async () => { const b = page.getByRole('button', { name: 'التالي' }); await reach(b); await b.click(); n++; };
  let step = 1; stepScreens.push(await screens());
  for (const [i, [s, loc, act]] of STEPS_FILL.entries()) {
    if (variant === 'B' && s !== step) { await next(); step = s; stepScreens.push(await screens()); if (await page.locator('.esum').count()) return { stoppedAtStep: step - 1, n, scrolled }; }
    if (i === skip) continue;
    const l = loc(page); await reach(l); await act(l, page); n++;
  }
  const submit = page.getByRole('button', { name: 'إرسال الطلب' });
  const filledScreens = await screens();
  await reach(submit); await submit.click(); n++;
  return { n, scrolled, stepScreens, filledScreens };
}

async function errorView(page) {
  return page.evaluate(() => {
    const s = document.querySelector('.esum'); if (!s) return null;
    const inView = e => { const r = e.getBoundingClientRect(); return r.top >= 0 && r.top < innerHeight && r.bottom > 0; };
    const err = document.querySelector('.err');
    return { summaryVisible: inView(s.querySelector('h2')) && inView(s.querySelector('li')), summaryFocused: document.activeElement === s,
      errorsListed: s.querySelectorAll('li').length, summaryScreens: +(s.getBoundingClientRect().height / innerHeight).toFixed(2),
      firstInlineErrorVisible: !!err && inView(err) };
  });
}

test.describe('careers · A/B measurement', () => {
  test('single page (A) vs short multi-step (B) at 360/390/430 → evidence JSON @careers @measure', async ({ browser }, ti) => {
    onlyOn(ti, 'm390');
    test.skip(ti.project.name.split('-')[0] !== 'chromium', 'measured once, in Chromium');
    test.setTimeout(180_000);
    const out = { spec: 'M28 §67 — single structured page vs short multi-step; owner delegated the choice to testing',
      method: ['Same 19 owner fields, same order, same intro block; Jordanian path (1 conditional field) and 3 uploaded files.',
        'interactionsToSubmit = Playwright actions on the happy path (fill/select/check/upload = 1 each) + step buttons + submit.',
        'userScrollScreens = sum of the minimal scrolls needed to bring each control into view (16px margin) ÷ viewport height; programmatic scroll by the page itself is not counted.',
        'pageScreens = document height ÷ viewport height (A: empty and filled; B: each step on entry).',
        'Error visibility: empty submit (A) / empty step 1 (B), and a realistic miss (only المنطقة left empty). "Visible" = in the viewport with no extra scrolling.'],
      results: {} };
    for (const [w, h] of VPS) {
      const ctx = await browser.newContext({ viewport: { width: w, height: h }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
      const page = await ctx.newPage(); const res = {};
      for (const v of ['A', 'B']) {
        const file = v === 'A' ? 'form-a.html' : 'form-b.html';
        await page.goto(C + file);
        const emptyScreens = +(await page.evaluate(() => document.documentElement.scrollHeight / innerHeight)).toFixed(2);
        const happy = await run(page, v);
        await expect(page).toHaveURL(/success\.html$/);
        await page.goto(C + file);
        const b = page.getByRole('button', { name: v === 'A' ? 'إرسال الطلب' : 'التالي' });
        let y0 = await page.evaluate(() => scrollY); await b.scrollIntoViewIfNeeded(); const scrollToFirstButton = +(((await page.evaluate(() => scrollY)) - y0) / h).toFixed(2);
        await b.click();
        const emptyErr = await errorView(page);
        await page.goto(C + file);
        const miss = await run(page, v, { skip: 11 }); // leave only المنطقة empty
        const missErr = await errorView(page);
        res[v] = {
          pageScreensEmpty: emptyScreens, ...(v === 'A' ? { pageScreensFilled: happy.filledScreens } : { stepScreens: happy.stepScreens, maxStepScreens: Math.max(...happy.stepScreens) }),
          interactionsToSubmit: happy.n, userScrollScreens: +(happy.scrolled / h).toFixed(2),
          emptySubmit: { scrollBeforeFirstFeedbackScreens: scrollToFirstButton, ...emptyErr },
          realisticMiss: { caughtAtStep: v === 'B' ? miss.stoppedAtStep : 'submit', ...missErr },
        };
      }
      out.results[`${w}x${h}`] = res; await ctx.close();
    }
    const vals = Object.values(out.results);
    out.summary = {
      interactions: { A: vals[0].A.interactionsToSubmit, B: vals[0].B.interactionsToSubmit },
      userScrollScreens: Object.fromEntries(Object.entries(out.results).map(([k, r]) => [k, { A: r.A.userScrollScreens, B: r.B.userScrollScreens }])),
      firstErrorVisibleWithoutScroll: Object.fromEntries(Object.entries(out.results).map(([k, r]) => [k, { A: r.A.emptySubmit.summaryVisible && r.A.realisticMiss.summaryVisible, B: r.B.emptySubmit.summaryVisible && r.B.realisticMiss.summaryVisible }])),
    };
    await mkdir(new URL('../../../docs/careers/wireframes/evidence/', import.meta.url), { recursive: true });
    await writeFile(new URL('../../../docs/careers/wireframes/evidence/form-variant-measure.json', import.meta.url), JSON.stringify(out, null, 1) + '\n');
    await ti.attach('form-variant-measure.json', { body: JSON.stringify(out, null, 1), contentType: 'application/json' });
    for (const r of vals) for (const v of ['A', 'B']) { expect(r[v].emptySubmit.summaryFocused).toBe(true); expect(r[v].realisticMiss.errorsListed).toBe(1); }
  });
});
