// Owner Dashboard prototype contract (P04 · M25 phase F + M32 "wireframes for new owner modules").
// Pages: docs/dashboard/wireframes/html (generated by docs/dashboard/wireframes/tools/build.py), served on :4177 (playwright.config.mjs).
// Owner rules checked here: 7 sidebar groups (GAP-CLOSURE-PLAN §C), 5-item mobile bottom nav, Safe Mode on every screen (M32 §23),
// every number = DEMO DATA (DASH-024), GA4 / Search Console / GBP = PENDING INTEGRATION, actionable warnings (M32 §40),
// owner-only V1 (no user / role management — M30), one design system (M34: tokens.css + wireframe-kit.css inlined).
// Titles avoid "— AR"/"— EN" on purpose so scripts/qa-matrix.mjs keeps counting only the menu pages.
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { DESKTOP_MIN } from '../../viewports.mjs';

const D = (process.env.SHELTER_DASHBOARD_URL || 'http://127.0.0.1:4177').replace(/\/$/, '') + '/';
const isDesk = ti => ti.project.use.viewport.width >= DESKTOP_MIN;
const onlyOn = (ti, name) => test.skip(!ti.project.name.endsWith(`-${name}`), `structure check: runs once on ${name}`);

// ---- frozen IA / vocabularies
const GROUPS = ['الرئيسية', 'المحتوى', 'التجارب', 'الأعمال', 'النمو', 'الجودة', 'النظام'];         // GAP-CLOSURE-PLAN §C
const BOTTOM = ['الرئيسية', 'المحتوى', 'التجارب', 'الأعمال', 'المزيد'];                             // §C mobile
const MORE = ['النمو', 'الجودة', 'النظام'];
const SCREENS = ['home', 'analytics', 'menu', 'product', 'impact', 'guard', 'branch', 'active', 'calendar', 'experience', 'family', 'media',
  'global-data', 'facts', 'parity', 'health', 'performance', 'a11y', 'security', 'privacy', 'seo', 'reputation', 'feedback', 'audit', 'safe-mode'];
const EXTRA = ['later'];                         // modules listed in the IA but wireframed in a later round
const DIALOGS = ['impact', 'guard', 'safe-mode']; // + m-more
const AVAIL = ['غير محدد — لا يظهر شيء للعميل', 'متوفر', 'غير متوفر — يبقى ظاهرًا مع «غير متوفر حاليًا»', 'غير متوفر — مخفي من المنيو']; // menu IA §9.6
const FACT_ST = ['APPROVED', 'VERIFIED', 'PENDING VERIFICATION', 'MISSING', 'SUPERSEDED', 'REJECTED'];   // M32 §03
const DEP_ST = ['GOOD', 'UPDATE AVAILABLE', 'SECURITY UPDATE', 'CRITICAL'];                             // M32 §38
const RUM_ST = ['GOOD', 'NEEDS IMPROVEMENT', 'POOR'];                                                     // M32 §11
const NA_SEV = ['critical', 'warning', 'info', 'security', 'seo'];                                        // M32 §39
const SAFE_KEEP = ['المنيو', 'الفروع والساعات', 'التواصل', 'التنقل', 'الصفحات الأساسية'];                // M32 §23
const PRESENT = ['شريط إعلان علوي', 'Hero Banner', 'ميزة في الصفحة الرئيسية', 'شريط عرض بعرض الصفحة', 'نافذة منبثقة (فقط عند الضرورة)']; // M31 §3
const REPLY = ['المراجعة', 'رد مقترح (AI ASSISTED)', 'تعديلك', 'اعتمادك', 'النشر (إذا سمح الربط)'];       // M32 §14
const NO_USERS = /المستخدمين|مستخدمون|مستخدم جديد|إضافة مستخدم|الصلاحيات|صلاحيات|الأدوار|إدارة الفريق|\bUsers?\b|\bRoles?\b|Permissions/i; // “مستخدمة في” (media usage) is not user management                        // M30: owner-only V1

// ---- one in-page audit used by every page × viewport (same rules as careers.spec.mjs, + <summary> targets)
async function audit(page, touch) {
  return page.evaluate(touch => {
    const vis = e => e.getClientRects().length > 0 && getComputedStyle(e).visibility !== 'hidden' && !e.closest('.vh');
    const own = e => [...e.childNodes].some(n => n.nodeType === 3 && n.textContent.trim());
    const SKIP = ['SCRIPT', 'STYLE', 'OPTION', 'OPTGROUP', 'SELECT', 'TEXTAREA', 'TITLE'];
    const texts = [...document.body.querySelectorAll('*')].filter(e => !SKIP.includes(e.tagName) && own(e) && vis(e));
    const name = e => `${e.tagName.toLowerCase()}${e.className && typeof e.className === 'string' ? '.' + e.className.split(' ')[0] : ''}: ${e.textContent.trim().slice(0, 30)}`;
    const tiny = [...new Set(texts.filter(e => parseFloat(getComputedStyle(e).fontSize) < 12).map(name))];
    const clipped = texts.filter(e => {
      const cs = getComputedStyle(e); if (e.clientWidth === 0 || ['auto', 'scroll'].includes(cs.overflowX)) return false;
      return e.scrollWidth - e.clientWidth > 1 || (e.scrollHeight - e.clientHeight > 1 && cs.overflowY !== 'visible');
    }).map(name);
    const TARGETS = 'a[href], button, select, textarea, summary, input:not([type=radio]):not([type=checkbox]):not([type=file]):not([type=hidden]), label.ds-check, [role=button]';
    const small = touch ? [...document.querySelectorAll(TARGETS)].filter(vis).filter(e => {
      const r = e.getBoundingClientRect(); return r.width < 43.5 || r.height < 43.5;
    }).map(name) : [];
    const controls = [...document.querySelectorAll('input:not([type=hidden]), select, textarea')];
    const unlabeled = controls.filter(e => {
      const l = [...(e.labels || [])].map(x => x.textContent.trim()).join('');
      const by = (e.getAttribute('aria-labelledby') || '').split(/\s+/).filter(Boolean).map(id => document.getElementById(id)?.textContent.trim() || '').join('');
      return !(l || by || (e.getAttribute('aria-label') || '').trim());
    }).map(e => e.id || e.name || e.type);
    const dialogs = [...document.querySelectorAll('[role=dialog]')].filter(vis).map(d => {
      const b = d.getBoundingClientRect(), x = d.querySelector('.x')?.getBoundingClientRect(), body = d.querySelector('.dbody');
      const foot = [...d.querySelectorAll('.dfoot .ds-btn')].map(e => e.getBoundingClientRect());
      return {
        inside: b.top >= -1 && b.left >= -1 && b.right <= innerWidth + 1 && b.bottom <= innerHeight + 1,
        scrollable: !body || body.scrollHeight <= body.clientHeight + 1 || ['auto', 'scroll'].includes(getComputedStyle(body).overflowY),
        bodyUsable: !body || body.clientHeight >= Math.min(80, body.scrollHeight),
        close: !!x && x.top >= 0 && x.bottom <= innerHeight + 1 && x.width >= 44 && x.height >= 44,
        footer: foot.every(r => r.top >= 0 && r.bottom <= innerHeight + 1),
        labelled: !!d.getAttribute('aria-labelledby') && !!document.getElementById(d.getAttribute('aria-labelledby'))?.textContent.trim(),
      };
    });
    return { lang: document.documentElement.lang, dir: document.documentElement.dir, overflowX: document.documentElement.scrollWidth > innerWidth + 1,
      tiny, clipped, small, unlabeled, dialogs, h1: document.querySelectorAll('h1').length, title: document.title };
  }, touch);
}

async function contract(page, ti, file) {
  await page.goto(D + file + '.html');
  const r = await audit(page, !!ti.project.use.hasTouch);
  expect.soft(r.lang, 'lang').toBe('ar');
  expect.soft(r.dir, 'dir').toBe('rtl');
  expect.soft(r.title, 'title must not look like a menu page').not.toMatch(/— (AR|EN)/);
  expect.soft(r.h1, 'exactly one h1').toBe(1);
  expect.soft(r.overflowX, 'horizontal overflow').toBe(false);
  expect.soft(r.clipped, 'clipped text').toEqual([]);
  expect.soft(r.tiny, 'text < 12px').toEqual([]);
  expect.soft(r.small, 'touch targets < 44px').toEqual([]);
  expect.soft(r.unlabeled, 'controls without a label').toEqual([]);
  for (const d of r.dialogs) expect.soft(d, 'dialog fits the screen').toEqual({ inside: true, scrollable: true, bodyUsable: true, close: true, footer: true, labelled: true });
  const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).analyze();
  const blocking = axe.violations.filter(v => ['serious', 'critical'].includes(v.impact));
  if (blocking.length) await ti.attach(`axe-${file}.json`, { body: JSON.stringify(blocking, null, 2), contentType: 'application/json' });
  expect.soft(blocking.map(v => `${v.id} (${v.nodes.length}): ${v.nodes[0]?.target}`), 'axe serious/critical').toEqual([]);
  return r;
}

// ---- responsive + a11y: every screen on every viewport (desktop layout ≥ 1024 → d-*, below → m-*)
test.describe('dashboard · screens (page × viewport)', () => {
  test('index · layout, labels, axe @dashboard @responsive @a11y', async ({ page }, ti) => { await contract(page, ti, 'index'); });
  for (const k of [...SCREENS, ...EXTRA]) test(`${k} · layout, labels, axe, dialogs @dashboard @responsive @a11y`, async ({ page }, ti) => {
    const r = await contract(page, ti, `${isDesk(ti) ? 'd' : 'm'}-${k}`);
    expect(r.dialogs.length, 'dialog screens show exactly one dialog').toBe(DIALOGS.includes(k) ? 1 : 0);
  });
  test('more sheet (mobile only) · layout, labels, axe @dashboard @responsive @a11y', async ({ page }, ti) => {
    test.skip(isDesk(ti), 'the “المزيد” sheet exists only below 1024px');
    const r = await contract(page, ti, 'm-more');
    expect(r.dialogs.length).toBe(1);
  });
});

// ---- shell contract (structure → 390 + 1440)
const files = kind => [...SCREENS, ...EXTRA, ...(kind === 'm' ? ['more'] : [])].map(s => `${kind}-${s}`);

test.describe('dashboard · shell contract', () => {
  for (const kind of ['d', 'm']) {
    test(`${kind === 'd' ? 'desktop: 7 collapsible sidebar groups + global search' : 'mobile: top bar + 5-item bottom nav + “المزيد” sheet'} · Safe Mode everywhere · no user management @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      for (const f of files(kind)) {
        await page.goto(D + f + '.html');
        const safe = page.locator('header [data-safe]');
        await expect(safe, `${f}: Safe Mode in the top bar`).toHaveCount(1);
        await expect(safe, f).toBeVisible();
        await expect(safe, f).toHaveText('وضع الأمان');
        await expect(safe, f).toHaveAttribute('href', `${kind}-safe-mode.html`);
        const links = await page.locator('a').allTextContents();
        expect(links.filter(t => NO_USERS.test(t)), `${f}: no user / role management (owner-only V1)`).toEqual([]);
        expect(await page.locator('input[type=password]').count(), f).toBe(0);
        if (kind === 'd') {
          const groups = page.locator('nav.dside [data-group]');
          expect(await groups.locator('.gname').allTextContents(), `${f}: 7 groups`).toEqual(GROUPS);
          expect(await page.locator('nav.dside details[data-group]').count(), `${f}: 6 collapsible + home link`).toBe(6);
          await expect(page.getByRole('search').getByLabel('بحث في لوحة التحكم')).toHaveAttribute('type', 'search');
          expect(await page.locator('.bnav').count()).toBe(0);
        } else {
          const items = page.locator('nav.bnav a');
          expect((await items.allTextContents()).map(t => t.trim()), `${f}: 5 bottom items`).toEqual(BOTTOM);
          await expect(page.locator('nav.bnav')).toBeVisible();
          expect(await page.locator('nav.dside').count()).toBe(0);
        }
      }
      if (kind === 'd') { // collapsible: a closed group opens on click and shows its items
        await page.goto(D + 'd-home.html');
        const quality = page.locator('nav.dside details[data-group=quality]');
        await expect(quality).not.toHaveAttribute('open', '');
        await expect(quality.getByRole('link', { name: 'صحة الموقع' })).toBeHidden();
        await quality.locator('summary').click();
        await expect(quality.getByRole('link', { name: 'صحة الموقع' })).toBeVisible();
        await page.goto(D + 'd-health.html');
        await expect(page.locator('nav.dside details[data-group=quality]')).toHaveAttribute('open', '');
        await expect(page.locator('nav.dside a[aria-current=page]')).toHaveText('صحة الموقع');
      } else {
        await page.goto(D + 'm-more.html');
        const sheet = page.getByRole('dialog', { name: 'المزيد' });
        expect((await sheet.locator('h3').allTextContents()).map(t => t.trim())).toEqual(MORE);
        await expect(sheet.getByLabel('بحث في لوحة التحكم')).toHaveAttribute('type', 'search');
        for (const t of ['التحليلات', 'صحة الموقع', 'الأمان', 'الخصوصية', 'البيانات العامة', 'سجل الحقائق', 'سجل التدقيق']) await expect(sheet.getByRole('link', { name: t, exact: true })).toBeVisible();
        await page.goto(D + 'm-health.html');
        await expect(page.locator('nav.bnav a[aria-current=page]')).toContainText('المزيد');
      }
    });

    test(`${kind}: every number is DEMO-labelled · nothing is LIVE · freshness on data cards @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      for (const f of files(kind)) {
        await page.goto(D + f + '.html');
        const bad = await page.evaluate(() => [...document.querySelectorAll('[data-n]')].filter(n => {
          const s = n.closest('[data-demo]');
          return !s || ['MAIN', 'BODY'].includes(s.tagName) || !/DEMO DATA/.test(s.querySelector('.demo')?.textContent || '');
        }).map(n => n.textContent.trim()));
        expect(bad, `${f}: numbers outside a DEMO-labelled block`).toEqual([]);
        if (await page.locator('[data-n]').count()) await expect(page.locator('.demo-banner').first(), `${f}: page-level DEMO banner`).toContainText('DEMO DATA');
        expect(await page.locator('body').textContent(), `${f}: no LIVE data in a prototype`).not.toMatch(/LIVE DATA/);
        const noFresh = await page.locator('.dcard[data-demo]').evaluateAll(cs => cs.filter(c => !/آخر تحديث/.test(c.querySelector('.fresh')?.textContent || '')).map(c => c.id));
        expect(noFresh, `${f}: data cards without “آخر تحديث”`).toEqual([]);
      }
    });

    test(`${kind}: internal links and anchors resolve (no dead links in the wireframes) @dashboard @structure`, async ({ request }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      test.setTimeout(120_000);
      const html = new Map(); // file → source (fetched once)
      const get = async file => {
        if (!html.has(file)) { const r = await request.get(D + file); html.set(file, r.status() === 200 ? await r.text() : null); }
        return html.get(file);
      };
      const dead = [];
      for (const f of ['index', ...files(kind)].map(x => x + '.html')) {
        const src = await get(f);
        const hrefs = [...src.matchAll(/<a\b[^>]*\shref="([^"]*)"/g)].map(m => m[1].replace(/&amp;/g, '&'));
        for (const h of hrefs) {
          if (h.startsWith('../')) continue; // careers / franchise wireframes live in their own folders (served elsewhere)
          const path = h.split(/[?#]/)[0] || f;
          const hash = h.includes('#') ? h.split('#')[1].split('?')[0] : '';
          const target = await get(path);
          if (target === null) dead.push(`${f} → ${h} (404)`);
          else if (hash && !target.includes(`id="${hash}"`)) dead.push(`${f} → ${h} (no #${hash})`);
        }
      }
      expect(dead).toEqual([]);
    });
  }
});

// ---- module contracts (structure → 390 + 1440)
test.describe('dashboard · owner spec contract', () => {
  for (const kind of ['d', 'm']) {
    test(`${kind}: command center — Needs Attention grouped and clickable, Active Now, visits, sources, owner language @dashboard @structure`, async ({ page, request }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-home.html`);
      expect(await page.locator('#na .na-grp').evaluateAll(gs => gs.map(g => g.dataset.sev))).toEqual(NA_SEV);
      const items = page.locator('#na .na-item');
      expect(await items.count()).toBeGreaterThanOrEqual(NA_SEV.length);
      const links = await items.evaluateAll(is => is.map(i => { const a = i.querySelector(':scope > a.na-link'); return a ? a.getAttribute('href') : null; }));
      expect(links.filter(l => !l), 'every Needs-Attention item is a link').toEqual([]);
      for (const l of links) expect((await request.get(D + l.split(/[?#]/)[0])).status(), l).toBe(200);
      expect(await page.locator('#na .na-sum a').count(), 'counts per group are links').toBe(NA_SEV.length);
      await expect(page.locator('#na')).toContainText('صورة الصفحة الرئيسية كبيرة وتبطئ تحميل الصفحة');
      const adv = page.locator('#na details.adv').first();
      await expect(adv.locator('summary')).toHaveText('تفاصيل متقدمة');
      await expect(adv.locator('p')).toBeHidden();
      await adv.locator('summary').click();
      await expect(page.locator('#na details.adv[open] p').first()).toBeVisible();
      await expect(page.locator('#na')).toContainText('Hero LCP resource 2.8MB');
      expect(await page.locator('#live .tile').count()).toBeGreaterThanOrEqual(2);
      await expect(page.locator('#live')).toContainText('يبدأ التالي');
      await expect(page.locator('#live')).toContainText('ينتهي التالي');
      expect((await page.locator('#visits .kpi-l').allTextContents())).toEqual(['زيارات اليوم', 'زيارات هذا الأسبوع', 'زيارات هذا الشهر']);
      for (const s of ['GA4', 'Search Console', 'Google Business Profile']) await expect(page.locator(`#sources .pi[data-src="${s}"]`)).toContainText('PENDING INTEGRATION');
      for (const t of ['تغيير سعر صنف', 'تغيير توفر صنف', 'تعديل ساعات فرع', 'تشغيل أو إيقاف حملة', 'رفع صورة', 'مراجعة صحة الموقع'])
        await expect(page.getByRole('link', { name: t, exact: true }), `phone task (M26): ${t}`).toBeVisible();
    });

    test(`${kind}: analytics — GA4 PENDING INTEGRATION, presets + comparison, one small chart (desktop) or a summary (mobile) @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-analytics.html`);
      await expect(page.locator('#source .pi[data-src=GA4]')).toContainText('PENDING INTEGRATION');
      expect(await page.locator('#range option').allTextContents()).toEqual(['اليوم', 'أمس', 'آخر 7 أيام', 'آخر 30 يومًا', 'هذا الشهر', 'الشهر السابق', 'فترة مخصصة']);
      expect(await page.locator('#summary a.kpi').count()).toBe(10);
      expect(await page.locator('svg[role=img]').count(), 'at most one chart').toBe(kind === 'd' ? 1 : 0);
      if (kind === 'd') await expect(page.locator('#trend details.adv summary')).toHaveText('عرض كجدول');
    });

    test(`${kind}: menu list + product editor + change impact + publish guard @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-menu.html`);
      if (kind === 'd') expect(await page.locator('.tbl tbody tr').count()).toBe(8); else { expect(await page.locator('table').count()).toBe(0); expect(await page.locator('#items .rcard').count()).toBe(8); }
      await expect(page.getByRole('link', { name: 'نشر التغييرات' })).toHaveAttribute('href', `${kind}-impact.html`);
      await page.goto(`${D}${kind}-product.html`);
      for (const l of ['الاسم بالعربية', 'الاسم بالإنجليزية', 'السعر الجديد', 'الفئة', 'القسم الفرعي']) await expect(page.getByLabel(l, { exact: true })).toBeVisible();
      await expect(page.locator('#price .sfx')).toHaveText('د.أ');
      for (const b of ['SHELTER COFFEE DRIVE', 'SHELTER COFFEE HOUSE']) {
        const g = page.getByRole('group', { name: b, exact: true });
        expect((await g.locator('label').allTextContents()).map(t => t.trim()), b).toEqual(AVAIL);
      }
      await expect(page.locator('#image').getByRole('link', { name: 'اختيار من مركز الوسائط' })).toBeVisible();
      for (const l of ['جديد', 'موسمي']) await expect(page.getByLabel(l, { exact: true })).toHaveAttribute('type', 'checkbox');
      await expect(page.getByRole('link', { name: 'نشر…' })).toHaveAttribute('href', `${kind}-impact.html`);
      await expect(page.getByRole('button', { name: 'أرشفة' })).toBeVisible();
      await expect(page.getByRole('link', { name: 'سجل النسخ' })).toHaveAttribute('href', `${kind}-audit.html#versions`);
      expect(await page.getByRole('button', { name: /^حذف/ }).count(), 'archive, never delete').toBe(0);
      await page.goto(`${D}${kind}-impact.html`);
      const imp = page.getByRole('dialog');
      await expect(imp).toContainText('هذا التغيير يؤثر على:');
      expect(await imp.locator('#impact-list li').count()).toBeGreaterThanOrEqual(3);
      await expect(imp.getByRole('link', { name: 'متابعة إلى فحص النشر' })).toHaveAttribute('href', `${kind}-guard.html`);
      await page.goto(`${D}${kind}-guard.html`);
      const g = page.getByRole('dialog', { name: 'فحص النشر' });
      expect(await g.locator('[data-guard]').evaluateAll(s => s.map(x => x.dataset.guard))).toEqual(['BLOCKING', 'WARNING', 'PASS']);
      await expect(g.getByRole('button', { name: 'نشر رغم التحذيرات' })).toBeDisabled();
      await expect(g.getByLabel('سبب التجاوز (يُسجَّل في سجل التدقيق)')).toBeVisible();
      await expect(g.locator('[data-guard=BLOCKING] a')).toHaveAttribute('href', `${kind}-product.html#name-en`);
    });

    test(`${kind}: branch editor — regular / special hours, temporary closure, contact from Global Data @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-branch.html`);
      expect(await page.locator('#hours input[type=time]').count(), '7 days × open/close').toBe(14);
      for (const d of ['السبت', 'الجمعة']) for (const w of ['يفتح', 'يغلق']) await expect(page.getByLabel(new RegExp(`${d} — ${w}`))).toHaveCount(1);
      await expect(page.locator('#special')).toContainText('رمضان');
      for (const l of ['من تاريخ', 'إلى تاريخ', 'السبب']) await expect(page.locator('#special').getByLabel(l, { exact: true })).toBeVisible();
      await expect(page.getByLabel('الفرع مغلق مؤقتًا')).toHaveAttribute('type', 'checkbox');
      await expect(page.locator('#contact').getByRole('link', { name: 'تعديل في البيانات العامة' })).toHaveAttribute('href', `${kind}-global-data.html#contacts`);
      expect(await page.locator('#contact input').count(), 'phone / WhatsApp are not typed here').toBe(0);
    });

    test(`${kind}: experiences — Active Now, calendar, editor, Employee of the Month / SHELTER Family @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-active.html`);
      const cards = page.locator('.rcards > li[id^=exp-]');
      expect(await cards.count()).toBe(3);
      for (const c of await cards.all()) { await expect(c.getByRole('button', { name: 'أوقف الآن' })).toBeVisible(); await expect(c.getByLabel('الأولوية')).toBeVisible(); }
      await expect(page.locator('#collision')).toContainText('تعارض');
      await page.goto(`${D}${kind}-calendar.html`);
      expect((await page.locator('.seg a').allTextContents()).map(t => t.trim())).toEqual(['شهر', 'أسبوع', 'قائمة']);
      await expect(page.locator('.seg a[aria-current=page]')).toHaveText(kind === 'd' ? 'شهر' : 'قائمة');
      expect(await page.locator('#cal .coll').count(), 'collision markers').toBeGreaterThanOrEqual(2);
      if (kind === 'd') expect(await page.locator('table.cal tbody td[id^=d-]').count()).toBe(31);
      await page.goto(`${D}${kind}-experience.html`);
      expect((await page.getByRole('group', { name: 'شكل العرض' }).locator('label').allTextContents()).map(t => t.trim())).toEqual(PRESENT);
      for (const l of ['يبدأ — التاريخ', 'يبدأ — الوقت', 'ينتهي — التاريخ', 'ينتهي — الوقت', 'الأولوية', 'أرني الموقع في تاريخ']) await expect(page.getByLabel(l, { exact: true })).toBeVisible();
      expect((await page.getByRole('group', { name: 'الفروع' }).locator('label').allTextContents()).map(t => t.trim())).toEqual(['كل الفروع', 'SHELTER COFFEE DRIVE', 'SHELTER COFFEE HOUSE']);
      await expect(page.locator('#preview')).toContainText('المعاينة لا تغيّر الموقع الحي');
      await page.goto(`${D}${kind}-family.html`);
      expect(await page.locator('#eom-s option').allTextContents()).toEqual(['مسودة', 'مجدول', 'نشط', 'منتهي', 'مؤرشف']);
      const noConsent = page.locator('#family').getByRole('button', { name: 'نشر' }).and(page.locator('[disabled]'));
      expect(await noConsent.count(), 'publish blocked without recorded consent').toBe(1);
      await expect(page.locator('#family')).toContainText('لا راتب، ولا هاتف، ولا رقم هوية');
    });

    test(`${kind}: media center rights + usage + press kit · global data impact · fact registry statuses · parity @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-media.html`);
      for (const l of ['المصور', 'المصدر', 'حقوق الاستخدام', 'موافقة الأشخاص الظاهرين', 'صالحة للموقع', 'صالحة للإعلانات', 'القيود', 'تنتهي الحقوق في', 'النص البديل بالعربية', 'النص البديل بالإنجليزية'])
        await expect(page.getByLabel(l, { exact: true }), l).toHaveCount(1);
      expect(await page.locator('#asset .rows a').count(), 'used-in links').toBe(3);
      await expect(page.locator('#press-kit')).toContainText('Press Kit');
      await expect(page.locator('#asset').getByRole('button', { name: 'أرشفة' })).toBeDisabled();
      await page.goto(`${D}${kind}-global-data.html`);
      await expect(page.locator('#edit-phone')).toContainText('هذا التغيير يؤثر على:');
      expect(await page.locator('#gd-impact li').allTextContents()).toEqual(['التذييل (Footer)', 'صفحة التواصل', 'صفحة DRIVE', 'صفحة HOUSE', 'روابط واتساب', 'بيانات Schema', 'صفحة الشراكات', 'صفحة التوظيف']);
      await page.goto(`${D}${kind}-facts.html`);
      expect((await page.locator('#fact-status .ds-badge').allTextContents()).map(t => t.trim())).toEqual(FACT_ST);
      for (const s of FACT_ST) await expect(page.locator('#facts .rcards, #facts table').first()).toContainText(s);
      await page.goto(`${D}${kind}-parity.html`);
      expect(await page.locator('#parity a.ds-chip').count()).toBe(6);
      await expect(page.locator('main')).toContainText('لا ترجمة آلية ولا نشر تلقائي');
    });

    test(`${kind}: quality — site health, performance (RUM p75), accessibility, security, privacy @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-health.html`);
      for (const c of ['حداثة المحتوى', 'الروابط', 'Schema', 'Sitemap', 'الفهرسة', 'النسخ الاحتياطي', 'الاعتماديات']) await expect(page.locator('#issues .chips')).toContainText(c);
      await expect(page.locator('#backups')).toContainText('آخر اختبار استعادة');
      expect((await page.locator('#deps .chips .ds-badge').allTextContents()).map(t => t.trim())).toEqual(DEP_ST);
      await expect(page.locator('#index .pi[data-src="Search Console"]')).toContainText('PENDING INTEGRATION');
      await page.goto(`${D}${kind}-performance.html`);
      for (const s of RUM_ST) await expect(page.locator('main')).toContainText(s);
      for (const m of ['LCP', 'INP', 'CLS', 'p75']) await expect(page.locator('main')).toContainText(m);
      const alerts = page.locator('#alerts .rcard');
      expect(await alerts.count()).toBe(3);
      for (const t of ['المشكلة', 'الصفحة', 'الأجهزة', 'السبب المرجّح (بدليل)', 'الإجراء المقترح']) await expect(alerts.first()).toContainText(t);
      await expect(page.locator('#alerts')).toContainText('لن نخمّن السبب');
      await page.goto(`${D}${kind}-a11y.html`);
      await expect(page.locator('main')).toContainText('WCAG 2.2 AA');
      for (const t of ['آلي', 'يدوي']) await expect(page.locator('#a11y-issues')).toContainText(t);
      await page.goto(`${D}${kind}-security.html`);
      for (const t of ['SSL', 'رؤوس الأمان', 'Passkey', 'المصادقة الثنائية', 'نشاط الدخول', 'الجلسات النشطة', 'سياسة المحتوى (CSP)', 'آخر نسخة احتياطية']) await expect(page.locator('main')).toContainText(t);
      expect(await page.locator('main').textContent(), 'no secrets').not.toMatch(/(api[_ -]?key|secret|token|password)\s*[:=]/i);
      await page.goto(`${D}${kind}-privacy.html`);
      for (const id of ['inventory', 'consents', 'retention', 'requests', 'cookies', 'policies']) await expect(page.locator(`#${id}`)).toBeVisible();
      await expect(page.locator('#retention')).toContainText('لا حذف تلقائي');
    });

    test(`${kind}: growth & business — SEO + site search + opportunities, reputation, feedback, audit, safe mode @dashboard @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      await page.goto(`${D}${kind}-seo.html`);
      await expect(page.locator('#gsc .pi[data-src="Search Console"]')).toContainText('PENDING INTEGRATION');
      for (const t of ['الأكثر بحثًا', 'بحث بلا نتائج', 'بحث صاعد']) await expect(page.locator('#search')).toContainText(t);
      await expect(page.locator('#opps')).toContainText('أنت تقرر');
      await expect(page.locator('#opps')).toContainText('لا مقالات تلقائية');
      await page.goto(`${D}${kind}-reputation.html`);
      expect(await page.locator('.pi[data-src="Google Business Profile"]').count()).toBeGreaterThanOrEqual(3);
      expect((await page.locator('#reply-flow li').allTextContents()).map(t => t.trim())).toEqual(REPLY);
      await expect(page.getByRole('button', { name: 'نشر على Google' })).toBeDisabled();
      await expect(page.getByLabel('الرد المقترح — يمكنك تعديله')).toBeVisible();
      await page.goto(`${D}${kind}-feedback.html`);
      await expect(page.locator('#topics')).toContainText('AI ASSISTED ANALYSIS');
      await page.goto(`${D}${kind}-audit.html`);
      const log = page.locator('#log');
      for (const t of ['قبل', 'بعد', 'نشر رغم تحذير', 'وضع الأمان', 'تغيير سعر']) await expect(log).toContainText(t);
      await expect(page.locator('#versions')).toContainText('استعادة كمسودة');
      await page.goto(`${D}${kind}-safe-mode.html`);
      const dlg = page.getByRole('dialog', { name: 'تفعيل وضع الأمان؟' });
      expect(await dlg.locator('#safe-keep li').allTextContents()).toEqual(SAFE_KEEP);
      await expect(dlg.getByRole('button', { name: 'تفعيل وضع الأمان' })).toBeVisible();
      await expect(dlg).toContainText('وضع الأمان لا يغلق الموقع');
    });
  }

  test('one design system (M34): shared tokens + wireframe kit inlined, no raw colours / px sizes in page CSS @dashboard @structure', async ({ page }, ti) => {
    onlyOn(ti, 'd1440');
    for (const f of ['index', 'd-home', 'm-home', 'd-calendar', 'm-guard']) {
      await page.goto(D + f + '.html');
      const css = await page.locator('style').textContent();
      expect(css, f).toContain('--container-dashboard');      // tokens.css
      expect(css, f).toContain('.ds-btn--primary');           // wireframe-kit.css
      const page_css = css.split('/* ---- dashboard page-level rules (tokens only) ---- */')[1] || '';
      expect(page_css.length, `${f}: page-level block present`).toBeGreaterThan(100);
      expect(page_css.match(/#[0-9a-f]{3,8}\b|rgba?\(/gi) || [], `${f}: raw colours in page CSS`).toEqual([]);
      expect(page_css.match(/(font-size|border-radius|padding|margin|gap)\s*:[^;}]*\d+px/g) || [], `${f}: raw px sizes in page CSS`).toEqual([]);
      expect(await page.locator('[style]').count(), `${f}: no inline styles`).toBe(0);
    }
  });
});
