// Franchise / Partnership prototype contract (M29 deliverables 8–11 + application form A/B + Owner Dashboard «الشراكات» module, M30 owner-only V1).
// Pages: docs/franchise/wireframes/html (generated by docs/franchise/wireframes/tools/build.py), served on :4176 (playwright.config.mjs).
// Content rules come from M29 (§03 approved facts, §08–§09 no claims / no financial terms, §04 no territory labels, §23 no response-time
// promise, §25 FAQ neutral answers only, §34 FR number, §35 success page) and docs/franchise/02–04. The tests fail if a wireframe breaks one.
// Titles avoid "— AR"/"— EN" on purpose so scripts/qa-matrix.mjs keeps counting only the menu pages.
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { DESKTOP_MIN } from '../../viewports.mjs';

const F = (process.env.SHELTER_FRANCHISE_URL || 'http://127.0.0.1:4176').replace(/\/$/, '') + '/';
const isDesk = ti => ti.project.use.viewport.width >= DESKTOP_MIN;
const onlyOn = (ti, name) => test.skip(!ti.project.name.endsWith(`-${name}`), `structure check: runs once on ${name}`);
const LANGS = ['ar', 'en'];
const FORMS = ['form-a', 'form-a-errors', 'form-a-network', 'form-b', 'form-b-s2', 'form-b-s3', 'form-b-s4', 'form-b-s5', 'form-b-errors', 'form-b-network'];
const PUBLIC = ['index', ...LANGS.flatMap(l => ['franchise', ...FORMS, 'success'].map(p => `${l}-${p}`))];
const DASH = ['overview', 'list', 'list-filters', 'quickview', 'application', 'meetings', 'archived', 'settings'];
const ALL = [...PUBLIC, ...DASH.flatMap(k => [`d-${k}`, `m-${k}`])];

// ---- owner / doc values (M29 · docs/franchise/02–04)
const H1 = { ar: 'كن شريكًا في نمو SHELTER COFFEE', en: 'Grow with SHELTER COFFEE' };
const CTA1 = { ar: 'ابدأ طلب الشراكة', en: 'Start your partnership application' };
const CTA2 = { ar: 'تعرّف على SHELTER', en: 'Discover SHELTER' };
const SUBMIT = { ar: 'إرسال الطلب', en: 'Submit application' };
const NEXT = { ar: 'التالي', en: 'Next' };
const PV = 'PENDING VERIFICATION — Franchise Master';
const MEDIA = 'MEDIA PENDING OWNER APPROVAL';
const LEGAL = 'PENDING LEGAL REVIEW';
const IA = ['top', 'who', 'experiences', 'why', 'system', 'midband', 'criteria', 'journey', 'support', 'markets', 'faq', 'apply', 'final'];
const CRITERIA = {
  ar: ['الالتزام بهوية SHELTER وقيمها', 'الجدية في الاستثمار والتشغيل', 'قدرة إدارية مناسبة', 'فهم السوق المحلي', 'الالتزام بمعايير الجودة', 'الالتزام بمعايير التشغيل', 'الرغبة في علاقة طويلة المدى'],
  en: ["Commitment to SHELTER's identity and values", 'Serious about investing in and running the business', 'Suitable management capability', 'Understanding of the local market',
    'Commitment to quality standards', 'Commitment to operating standards', 'A wish to build a long-term relationship'],
};
const JOURNEY = {
  ar: ['طلب اهتمام', 'مراجعة أولية', 'اجتماع تعريفي', 'تقييم السوق والموقع', 'مناقشة النموذج', 'الموافقات', 'التعاقد', 'التجهيز والتدريب', 'الافتتاح'],
  en: ['Expression of interest', 'Initial review', 'Introductory meeting', 'Market & site assessment', 'Model discussion', 'Approvals', 'Agreement', 'Setup & training', 'Opening'],
};
const FAQ_VISIBLE = ['faq-1', 'faq-2', 'faq-5', 'faq-6', 'faq-7']; // ✅ approved / neutral in docs/franchise/02 §4
const FAQ_PENDING = { ar: ['هل يجب أن تكون لدي خبرة في المقاهي؟', 'كيف يتم تقييم السوق أو الموقع؟', 'هل توفر SHELTER التدريب؟', 'هل توفر SHELTER دعمًا في التصميم والتجهيز؟', 'ما الخطوات بعد الموافقة الأولية؟'],
  en: ['Do I need café experience?', 'How are the market and the site assessed?', 'Does SHELTER provide training?', 'Does SHELTER support design and setup?', 'What are the steps after initial approval?'] };
// field matrix order (docs/franchise/03): 1–3 about · 4–6 market · 8 (+ optional note) 9 12 13 experience · 7 10 11 opportunity · consent
const KEYS = ['name', 'phone', 'email', 'country', 'city', 'market', 'years', 'expnote', 'owns', 'company', 'website', 'interest', 'location', 'message', 'consent'];
const REQUIRED = ['name', 'phone', 'email', 'country', 'city', 'market', 'years', 'owns', 'interest', 'location', 'message', 'consent'];
const OPTIONAL = ['expnote', 'company', 'website'];
const LABELS = {
  ar: { name: 'الاسم الكامل', phone: 'رقم الهاتف', email: 'البريد الإلكتروني', country: 'الدولة', city: 'المدينة', market: 'السوق أو المنطقة المهتم بها', years: 'سنوات الخبرة في الأعمال',
    expnote: 'نبذة عن خبرتك', company: 'اسم الشركة', website: 'موقع الشركة الإلكتروني', interest: 'نوع الاهتمام بالشراكة', message: 'رسالة تعريفية قصيرة' },
  en: { name: 'Full name', phone: 'Phone number', email: 'Email', country: 'Country', city: 'City', market: 'Market or area of interest', years: 'Years of business experience',
    expnote: 'About your experience', company: 'Company name', website: 'Company website', interest: 'Partnership interest', message: 'Short introduction' },
};
const GROUPS_Q = { ar: { owns: 'هل تملك أو تدير عملًا حاليًا؟', location: 'حالة الموقع المقترح' }, en: { owns: 'Do you currently own or manage a business?', location: 'Proposed location status' } };
const OPTS = { ar: { owns: ['نعم', 'لا'], location: ['لدي موقع محدد', 'أبحث عن موقع', 'لم أبدأ البحث بعد'] }, en: { owns: ['Yes', 'No'], location: ['I have a specific location', "I'm looking for a location", "I haven't started looking yet"] } };
const CONSENT = { ar: 'أوافق على قيام SHELTER COFFEE بمعالجة البيانات الواردة في هذا الطلب لغرض دراسة طلب الشراكة والتواصل معي بشأنه.',
  en: 'I agree that SHELTER COFFEE may process the information in this application to review my partnership application and contact me about it.' };
const DISCLAIMER = { ar: 'إرسال الطلب لا يمثل موافقة على منح الامتياز ولا التزامًا تعاقديًا.', en: 'Submitting this application is not an approval to grant a franchise and is not a contractual commitment.' };
const STEP_NAMES = { ar: ['عنك', 'السوق', 'الخبرة', 'الفرصة', 'المراجعة والإرسال'], en: ['About you', 'Market', 'Experience', 'Opportunity', 'Review & submit'] };
// dashboard (docs/franchise/04)
const D_NAV = ['نظرة عامة', 'الطلبات', 'الاجتماعات', 'الأرشيف', 'الإعدادات'];
const COLS = ['المتقدم', 'الدولة', 'المدينة', 'السوق المقترح', 'تاريخ الطلب', 'المرحلة', 'آخر تحديث'];
const SEARCH_BY = ['المتقدم', 'الهاتف', 'البريد', 'الدولة', 'المدينة', 'السوق', 'رقم الطلب'];
const FILTERS = ['المرحلة', 'الدولة', 'المدينة', 'تاريخ الطلب', 'السوق'];
const STAGES = ['تم الاستلام', 'مؤهل مبدئيًا', 'اجتماع', 'مراجعة السوق', 'مراجعة الموقع', 'موافق', 'مرحلة العقد', 'مغلق'];
const CODES = ['received', 'qualified', 'meeting', 'market_review', 'site_review', 'approved', 'contract', 'closed', 'archived'];
const APP_SECTIONS = ['بيانات الطلب', 'معلومات السوق', 'الملاحظات الداخلية', 'الاجتماعات', 'المرفقات', 'الإسناد', 'سجل المراحل', 'الطلبات السابقة', 'سجل التدقيق'];
const AUDIT_COLS = ['المنفّذ (Actor)', 'الإجراء (Action)', 'الهدف (Target)', 'الوقت (Timestamp)', 'قبل (Before)', 'بعد (After)'];

// ---- content rules (M29 §08, §09, §13–§25, §83)
const FORBIDDEN = ['مضمون', 'أفضل فرنشايز', 'فرصة العمر', 'أرباح', 'guaranteed', 'best franchise', 'أفضل', 'الأكبر', 'الأسرع', 'رقم 1', 'number one', 'largest', 'fastest',
  'proven', 'مثبت النجاح', 'Since 2022', 'منذ 2022', '2018', 'exclusive', 'حصري'];
const FIVE_DAYS = /(^|[^\d٠-٩])[5٥]\s*(أيام|يوم|days?|business days?)|خمسة أيام|five (business )?days/i;
const RESPONSE_TIME = /(خلال|within)\s*[\d٠-٩]+\s*(ساعة|ساعات|يوم|أيام|hours?|days?|business|weeks?|أسبوع)/i;
const CURRENCY = /\$|€|£|¥|\bJOD\b|\bUSD\b|\bEUR\b|د\.أ|دينار|dinar|dollar|دولار|ريال|درهم/i;
const FINANCIAL = /royalt|إتاوة|\bROI\b|العائد على الاستثمار|payback|فترة الاسترداد|revenue|الإيرادات|profit|ربح|net worth|الملاءة|رأس المال|\bcapital\b|capex|opex|territory fee|renewal fee|رسوم التجديد|investment range|نطاق الاستثمار|minimum store|contract duration|مدة العقد/i;
const TERRITORY = /متاح|حصري|مفتوح|محجوز|\bavailable\b|\bexclusive\b|\bopen\b|\breserved\b/i;

// ---- one in-page audit used by every page × viewport
async function audit(page, touch) {
  return page.evaluate(touch => {
    const vis = e => e.getClientRects().length > 0 && getComputedStyle(e).visibility !== 'hidden' && !e.closest('.vh');
    const own = e => [...e.childNodes].some(n => n.nodeType === 3 && n.textContent.trim());
    const SKIP = ['SCRIPT', 'STYLE', 'OPTION', 'OPTGROUP', 'SELECT', 'TEXTAREA', 'TITLE'];
    const texts = [...document.body.querySelectorAll('*')].filter(e => !SKIP.includes(e.tagName) && own(e) && vis(e));
    const name = e => `${e.tagName.toLowerCase()}${typeof e.className === 'string' && e.className ? '.' + e.className.split(' ')[0] : ''}: ${e.textContent.trim().slice(0, 40)}`;
    const tiny = [...new Set(texts.filter(e => parseFloat(getComputedStyle(e).fontSize) < 12).map(name))];
    const clipped = texts.filter(e => {
      const cs = getComputedStyle(e); if (e.clientWidth === 0 || ['auto', 'scroll'].includes(cs.overflowX)) return false;
      return e.scrollWidth - e.clientWidth > 1 || (e.scrollHeight - e.clientHeight > 1 && cs.overflowY !== 'visible');
    }).map(name);
    const TARGETS = 'a[href], button, select, textarea, input:not([type=radio]):not([type=checkbox]):not([type=file]):not([type=hidden]), label.ds-chip, label.ds-check, summary, [role=button]';
    const small = touch ? [...document.querySelectorAll(TARGETS)].filter(vis).filter(e => {
      const r = e.getBoundingClientRect(); return r.width < 43.5 || r.height < 43.5;
    }).map(name) : [];
    const controls = [...document.querySelectorAll('input:not([type=hidden]), select, textarea')];
    const unlabeled = controls.filter(e => {
      const l = [...(e.labels || [])].map(x => x.textContent.trim()).join('');
      const by = (e.getAttribute('aria-labelledby') || '').split(/\s+/).filter(Boolean).map(id => document.getElementById(id)?.textContent.trim() || '').join('');
      return !(l || by || (e.getAttribute('aria-label') || '').trim());
    }).map(e => e.id || e.name || e.type);
    const dialogs = [...document.querySelectorAll('[role=dialog]')].filter(vis).map(d => {
      const b = d.getBoundingClientRect(), x = d.querySelector('.x')?.getBoundingClientRect(), cs = getComputedStyle(d);
      const foot = [...d.querySelectorAll('.dlg-f .ds-btn')].map(e => e.getBoundingClientRect());
      return {
        inside: b.top >= -1 && b.left >= -1 && b.right <= innerWidth + 1 && b.bottom <= innerHeight + 1,
        scrollable: d.scrollHeight <= d.clientHeight + 1 || ['auto', 'scroll'].includes(cs.overflowY),
        close: !!x && x.top >= 0 && x.bottom <= innerHeight + 1 && x.width >= 44 && x.height >= 44,
        footer: foot.every(r => r.top >= 0 && r.bottom <= innerHeight + 1),
        labelled: !!d.getAttribute('aria-labelledby') && !!document.getElementById(d.getAttribute('aria-labelledby'))?.textContent.trim(),
      };
    });
    const hs = [...document.querySelectorAll('h1,h2,h3,h4,h5,h6')].filter(h => h.getClientRects().length && !h.closest('[hidden]')).map(h => +h.tagName[1]);
    const skips = hs.map((l, i) => (i && l - hs[i - 1] > 1 ? `h${hs[i - 1]}→h${l}` : null)).filter(Boolean);
    const wide = Math.round(Math.max(0, ...texts.filter(e => !e.closest('.wf-tag')).map(e => e.getBoundingClientRect().width)));
    return { lang: document.documentElement.lang, dir: document.documentElement.dir, overflowX: document.documentElement.scrollWidth > innerWidth + 1,
      tiny, clipped, small, unlabeled, dialogs, h1: document.querySelectorAll('h1').length, first: hs[0], skips, wide };
  }, touch);
}

async function contract(page, ti, file) {
  await page.goto(F + file + '.html');
  const r = await audit(page, !!ti.project.use.hasTouch);
  const en = file.startsWith('en-');
  expect.soft(r.lang, 'lang').toBe(en ? 'en' : 'ar');
  expect.soft(r.dir, 'dir').toBe(en ? 'ltr' : 'rtl');
  expect.soft(r.h1, 'exactly one h1').toBe(1);
  expect.soft(r.first, 'first heading is the h1').toBe(1);
  expect.soft(r.skips, 'heading levels never skip').toEqual([]);
  expect.soft(r.overflowX, 'horizontal overflow').toBe(false);
  expect.soft(r.clipped, 'clipped text').toEqual([]);
  expect.soft(r.tiny, 'text < 12px').toEqual([]);
  expect.soft(r.small, 'touch targets < 44px').toEqual([]);
  expect.soft(r.unlabeled, 'controls without a label').toEqual([]);
  for (const d of r.dialogs) expect.soft(d, 'dialog fits the screen').toEqual({ inside: true, scrollable: true, close: true, footer: true, labelled: true });
  if (!/^[dm]-/.test(file) && ti.project.use.viewport.width >= 1440) expect.soft(r.wide, 'no text box wider than the page container (max-width 1280)').toBeLessThanOrEqual(1280);
  const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']).analyze();
  const blocking = axe.violations.filter(v => ['serious', 'critical'].includes(v.impact));
  if (blocking.length) await ti.attach(`axe-${file}.json`, { body: JSON.stringify(blocking, null, 2), contentType: 'application/json' });
  expect.soft(blocking.map(v => `${v.id} (${v.nodes.length}): ${v.nodes[0]?.target}`), 'axe serious/critical').toEqual([]);
  return r;
}

test.describe('franchise · public pages (page × viewport)', () => {
  for (const p of PUBLIC) test(`${p} · layout, headings, labels, axe @franchise @responsive @a11y`, async ({ page }, ti) => { await contract(page, ti, p); });
});

test.describe('franchise · owner dashboard (desktop ≥ 1024 · mobile below)', () => {
  for (const k of DASH) test(`${k} · layout, headings, labels, axe, dialogs @franchise @responsive @a11y`, async ({ page }, ti) => {
    const r = await contract(page, ti, `${isDesk(ti) ? 'd' : 'm'}-${k}`);
    if (/filters|quickview/.test(k)) expect(r.dialogs.length, 'dialog present').toBe(1);
  });
});

// ---- behaviour on every viewport
const group = (page, name) => page.getByRole('group', { name: new RegExp(`^${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\*?$`), includeHidden: true });

test.describe('franchise · page behaviour', () => {
  test('sticky CTA (< 1024): hidden over the hero, shown after it, hidden inside the form; never on desktop @franchise', async ({ page }, ti) => {
    for (const l of LANGS) {
      await page.goto(`${F}${l}-franchise.html`);
      const st = page.locator('.sticky');
      await expect(st).toBeHidden();
      await page.locator('#journey').evaluate(e => e.scrollIntoView({ block: 'start' }));
      if (isDesk(ti)) { await page.waitForTimeout(200); await expect(st).toBeHidden(); continue; }
      await expect(st).toBeVisible();
      await expect(st.getByRole('link', { name: CTA1[l] })).toHaveAttribute('href', '#apply');
      const pad = await page.evaluate(() => parseFloat(getComputedStyle(document.body).paddingBottom));
      expect(pad, 'page reserves room for the bar').toBeGreaterThanOrEqual((await st.boundingBox()).height - 1);
      for (const sel of ['#apply', '#name', '#consent', '#apply button[type=submit]']) {
        await page.locator(sel).first().evaluate(e => e.scrollIntoView({ block: 'center' }));
        await expect(st, `hidden while ${sel} is on screen`).toBeHidden();
      }
      await page.locator('.fr-midband').evaluate(e => e.scrollIntoView({ block: 'center' }));
      await expect(st, 'one primary CTA per screen: hidden over the mid CTA band').toBeHidden();
    }
  });

  test('hero CTAs: primary goes to the form, secondary to «Who is SHELTER?»; language switch keeps the page @franchise', async ({ page }) => {
    for (const l of LANGS) {
      await page.goto(`${F}${l}-franchise.html`);
      await page.locator('[data-cta=hero]').click();
      await expect(page).toHaveURL(/#apply$/);
      await expect(page.locator('#apply-h')).toBeInViewport();
      await page.goto(`${F}${l}-franchise.html`);
      await page.locator('[data-cta=hero-secondary]').click();
      await expect(page.locator('#who-h')).toBeInViewport();
      await page.goto(`${F}${l}-franchise.html`);
      await page.getByRole('link', { name: l === 'ar' ? 'English' : 'العربية' }).click();
      await expect(page.locator('html')).toHaveAttribute('lang', l === 'ar' ? 'en' : 'ar');
      await expect(page.locator('h1')).toHaveText(H1[l === 'ar' ? 'en' : 'ar']);
    }
  });

  test('«Why partner» rows: accordion below 1024 (first open), all open on desktop @franchise @a11y', async ({ page }, ti) => {
    await page.goto(`${F}ar-franchise.html`);
    const btns = page.locator('#why .acc');
    await expect(btns).toHaveCount(3);
    if (isDesk(ti)) {
      for (let i = 0; i < 3; i++) { await expect(btns.nth(i)).toHaveAttribute('aria-expanded', 'true'); await expect(btns.nth(i)).toHaveAttribute('aria-disabled', 'true'); }
      await expect(page.locator('#why-p3')).toBeVisible();
      return;
    }
    await expect(btns.nth(0)).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('#why-p2')).toBeHidden();
    await btns.nth(1).click();
    await expect(btns.nth(1)).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('#why-p2')).toBeVisible();
  });

  test('FAQ: only approved answers in the page, native disclosure opens; pending ones only in the annotation outside <main> @franchise', async ({ page }) => {
    for (const l of LANGS) {
      await page.goto(`${F}${l}-franchise.html`);
      expect(await page.locator('#faq details').evaluateAll(ds => ds.map(d => d.id))).toEqual(FAQ_VISIBLE);
      const q = page.locator('#faq-6 summary');
      await q.click();
      await expect(page.locator('#faq-6')).toHaveAttribute('open', '');
      await expect(page.locator('#faq-6 .a')).toBeVisible();
      const main = await page.locator('main').textContent();
      for (const t of FAQ_PENDING[l]) expect(main, t).not.toContain(t);
      const anno = page.locator('aside .anno-hidden');
      expect(await anno.evaluate(e => !e.closest('main'))).toBe(true);
      for (const t of FAQ_PENDING[l]) await expect(anno).toContainText(t);
    }
  });
});

test.describe('franchise · form behaviour', () => {
  test('A: empty submit → focused error summary (role=alert), one link per required field, link moves focus; same on the page @franchise @a11y', async ({ page }) => {
    for (const l of LANGS) for (const file of [`${l}-form-a`, `${l}-franchise`]) {
      await page.goto(F + file + '.html');
      await page.getByRole('button', { name: SUBMIT[l], exact: true }).click();
      const sum = page.locator('.esum[role=alert]');
      await expect(sum).toBeFocused();
      await expect(sum).toBeInViewport();
      expect(await sum.locator('a').count(), file).toBe(REQUIRED.length);
      const inline = await page.locator('.err').evaluateAll(es => es.map(e => e.textContent.trim()));
      expect(inline.length).toBe(REQUIRED.length);
      expect(inline.every(t => t.startsWith(l === 'ar' ? 'خطأ:' : 'Error:'))).toBe(true); // text, not colour only
      await sum.getByRole('link').nth(4).click();
      await expect(page.locator('#city')).toBeFocused();
      await expect(page.locator('#city')).toHaveAttribute('aria-invalid', 'true');
      await expect(page.locator('#city')).toHaveAttribute('aria-describedby', /e-city/);
    }
  });

  test('B: next on an empty step → step error summary; 5 steps with progress; review lists the answers @franchise', async ({ page }) => {
    for (const l of LANGS) {
      await page.goto(`${F}${l}-form-b.html`);
      await expect(page.locator('.prog-t')).toHaveText(new RegExp(STEP_NAMES[l][0]));
      expect(await page.locator('.step').count()).toBe(5);
      await page.getByRole('button', { name: NEXT[l] }).click();
      await expect(page.locator('.esum[role=alert]')).toBeFocused();
      await expect(page.locator('.esum[role=alert]')).toBeInViewport();
      expect(await page.locator('.esum a').count()).toBe(3);
      await page.getByLabel(LABELS[l].name).fill(l === 'ar' ? 'متقدم تجريبي' : 'Sample Applicant');
      await page.getByLabel(LABELS[l].phone).fill('+962700000001');
      await page.getByLabel(LABELS[l].email).fill('applicant@example.com');
      await page.getByRole('button', { name: NEXT[l] }).click();
      await expect(page.locator('.prog-t')).toHaveText(new RegExp(STEP_NAMES[l][1]));
      await expect(page.locator('.esum')).toHaveCount(0);
      await page.goto(`${F}${l}-form-b-s5.html`);
      await expect(page.locator('.rv')).toHaveCount(4);
      await expect(page.locator('.review')).toContainText('applicant1@example.com');
      await page.locator('.rv').nth(1).getByRole('button').click();
      await expect(page.locator('.prog-t')).toHaveText(new RegExp(STEP_NAMES[l][1]));
    }
  });

  test('error state pages: summary links reach real fields; inline errors are text + border, not colour only @franchise @a11y', async ({ page }) => {
    for (const l of LANGS) for (const f of ['form-a-errors', 'form-b-errors']) {
      await page.goto(`${F}${l}-${f}.html`);
      const sum = page.locator('.esum[role=alert]');
      await expect(sum).toBeVisible();
      const links = await sum.locator('a').evaluateAll(as => as.map(a => ({ t: a.textContent.trim(), target: !!document.getElementById(a.hash.slice(1)) })));
      expect(links.length).toBeGreaterThan(0);
      expect(links.every(x => x.target && x.t)).toBe(true);
      const inline = await page.locator('.err').evaluateAll(es => es.map(e => e.textContent.trim()));
      expect(inline.length).toBe(links.length);
      expect(inline.every(t => t.startsWith(l === 'ar' ? 'خطأ:' : 'Error:'))).toBe(true);
      expect(await page.locator('[aria-invalid=true]').evaluateAll(es => es.every(e => (e.getAttribute('aria-describedby') || '').includes('e-')))).toBe(true);
    }
  });

  test('network error keeps every input and offers a retry @franchise', async ({ page }) => {
    for (const l of LANGS) for (const f of ['form-a-network', 'form-b-network']) {
      await page.goto(`${F}${l}-${f}.html`);
      const alert = page.locator('form [role=alert]').first();
      await expect(alert).toBeVisible();
      await expect(alert.getByRole('button')).toBeVisible();
      for (const k of ['name', 'phone', 'email', 'city', 'market', 'interest', 'message']) await expect(page.locator(`#${k}`), `${f} ${k}`).not.toHaveValue('');
      await expect(page.locator('#consent')).toBeChecked();
    }
  });

  test('getByLabel reaches every field in A, B and the page (AR + EN) @franchise @a11y', async ({ page }) => {
    for (const l of LANGS) for (const f of ['form-a', 'form-b', 'franchise']) {
      await page.goto(`${F}${l}-${f}.html`);
      for (const [k, lab] of Object.entries(LABELS[l])) expect(await page.getByLabel(lab).count(), `${f} ${k}`).toBe(1);
      expect(await page.getByLabel(CONSENT[l]).count()).toBe(1);
      for (const k of ['owns', 'location']) {
        const g = group(page, GROUPS_Q[l][k]);
        expect(await g.count(), `${f} ${k}`).toBe(1);
        for (const o of OPTS[l][k]) expect(await g.getByLabel(o, { exact: true }).count()).toBe(1);
      }
    }
  });
});

// ---- content contract: every page, once (viewport-independent)
test.describe('franchise · content contract (M29)', () => {
  test('all pages: no forbidden claims/words, no 5-day or response-time promise, no currency or financial terms, FR number only with SAMPLE @franchise @structure', async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    test.setTimeout(120_000);
    for (const f of ALL) {
      await page.goto(F + f + '.html');
      const text = await page.evaluate(() => {
        const parts = []; const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); // one string per text node: no false matches across nodes
        for (let n = w.nextNode(); n; n = w.nextNode()) if (!n.parentElement.closest('script,style')) parts.push(n.textContent);
        const attrs = [...document.querySelectorAll('[aria-label],[placeholder],[title],[value],[alt]')].map(e => ['aria-label', 'placeholder', 'title', 'value', 'alt'].map(a => e.getAttribute(a) || '').join(' '));
        return parts.join(' ') + ' ' + attrs.join(' ') + ' ' + document.title;
      });
      for (const w of FORBIDDEN) expect.soft(text.toLowerCase().includes(w.toLowerCase()), `${f}: «${w}»`).toBe(false);
      expect.soft(text, `${f}: 5-day promise`).not.toMatch(FIVE_DAYS);
      expect.soft(text, `${f}: response-time promise`).not.toMatch(RESPONSE_TIME);
      expect.soft(text, `${f}: currency`).not.toMatch(CURRENCY);
      expect.soft(text, `${f}: financial term`).not.toMatch(FINANCIAL);
      const fr = await page.evaluate(() => {
        const out = []; const w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
        for (let n = w.nextNode(); n; n = w.nextNode()) {
          if (!/FR-2026-00125/.test(n.textContent) || n.parentElement.closest('script')) continue;
          let ok = false;
          for (let a = n.parentElement; a && a !== document.body; a = a.parentElement) {
            if (a.querySelector('.sample') && /SAMPLE/.test(a.querySelector('.sample').textContent)) { ok = true; break; }
            if (a.tagName === 'TABLE') { ok = /SAMPLE/.test(a.caption?.textContent || ''); break; }
            if (['SECTION', 'MAIN', 'ASIDE'].includes(a.tagName) || a.getAttribute('role') === 'dialog') break;
          }
          out.push(ok);
        }
        return out;
      });
      expect.soft(fr.every(Boolean), `${f}: FR-2026-00125 without a SAMPLE label`).toBe(true);
      if (/-success$/.test(f)) expect.soft(fr.length, `${f}: application number shown`).toBe(1);
      expect.soft(await page.locator('img, picture, video, iframe, canvas').count(), `${f}: no images (MEDIA PENDING OWNER APPROVAL)`).toBe(0);
    }
  });
});

// ---- structure contract (viewport-independent → once)
test.describe('franchise · page structure (docs/franchise/02 §1)', () => {
  for (const l of LANGS) test(`${l} page: IA order, H1, CTAs, facts, sections, status markers @franchise @structure`, async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(`${F}${l}-franchise.html`);
    const ids = await page.locator('main').evaluate(m => [...m.children].map(c => c.id || (c.querySelector('.fr-midband') ? 'midband' : c.className)));
    expect(ids).toEqual(IA);
    expect(await page.evaluate(() => [...document.body.children].map(c => c.tagName.toLowerCase()).filter(t => ['main', 'footer', 'aside'].includes(t)))).toEqual(['main', 'footer', 'aside']);
    await expect(page.locator('h1')).toHaveText(H1[l]);
    await expect(page.locator('.hero .eyebrow')).toHaveText('FRANCHISE & PARTNERSHIPS');
    const pri = page.locator('main a.ds-btn--primary[href="#apply"]');
    expect(await pri.evaluateAll(as => as.map(a => a.dataset.cta))).toEqual(['hero', 'mid', 'final']); // 3 placements only (UX-F-03)
    for (const t of await pri.allTextContents()) expect(t.trim()).toBe(CTA1[l]);
    await expect(page.locator('.sticky a')).toHaveText(CTA1[l]);
    await expect(page.locator('[data-cta=hero-secondary]')).toHaveText(CTA2[l]);
    await expect(page.locator('[data-cta=hero-secondary]')).toHaveAttribute('href', '#who');
    await expect(page.locator('[data-cta=who-secondary]')).toHaveAttribute('href', '#experiences');
    await expect(page.locator('#apply a[href="#faq"]')).toHaveCount(1);
    const facts = await page.locator('#who .facts').textContent();
    for (const t of ['2019', l === 'ar' ? 'إربد، الأردن' : 'Irbid, Jordan', 'SHELTER COFFEE DRIVE', 'SHELTER COFFEE HOUSE']) expect(facts).toContain(t);
    await expect(page.locator('#who')).toContainText('شلتر كوفي');
    expect(await page.locator('#experiences h3').allTextContents()).toEqual(['SHELTER COFFEE DRIVE', 'SHELTER COFFEE HOUSE']);
    await expect(page.locator('#experiences')).not.toContainText(l === 'ar' ? 'اختر نموذج الفرنشايز' : 'Choose your franchise model');
    expect(await page.locator('#why .why-row').count()).toBe(3); // 3 editorial rows, not 9 identical cards
    expect(await page.locator('#why .why-row').evaluateAll(rs => rs.map(r => r.querySelectorAll('.ticks li').length))).toEqual([3, 3, 3]);
    expect(await page.locator('#system .sys li').count()).toBe(9);
    expect((await page.locator('#criteria .crit li').allTextContents()).map(t => t.trim())).toEqual(CRITERIA[l]);
    expect((await page.locator('#journey .tl .t').allTextContents()).map(t => t.replace(/^.*?:\s*/, '').trim())).toEqual(JOURNEY[l]);
    expect(await page.locator('#support .stages li').count()).toBe(9);
    for (const s of ['#why', '#system', '#criteria', '#journey', '#support']) await expect(page.locator(s), s).toContainText(PV);
    await expect(page.locator('#markets')).toContainText('PF-09');
    expect(await page.locator('#markets svg, #markets img, #markets iframe, #markets canvas, #markets [class*=map]').count(), 'no map').toBe(0);
    expect(await page.locator('#markets').evaluate(e => e.textContent)).not.toMatch(TERRITORY);
    for (const m of await page.locator('.ds-media').allTextContents()) expect(m).toContain(MEDIA);
    expect(await page.locator('.ds-media').count()).toBeGreaterThanOrEqual(7);
    await expect(page.locator('#apply form.app')).toHaveAttribute('data-variant', /^[AB]$/);
    await expect(page.locator('#disclaimer')).toContainText(DISCLAIMER[l]);
    await expect(page.locator('#disclaimer')).toContainText(LEGAL);
    await expect(page.locator('#h-consent')).toContainText('PENDING');
  });

  for (const l of LANGS) test(`${l} form: field matrix (1–11 required, 12–13 optional, no 14/15), consent + disclaimer, A = B fields, 5 steps @franchise @structure`, async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    for (const f of ['form-a', 'form-b']) {
      await page.goto(`${F}${l}-${f}.html`);
      expect(await page.locator('[data-f]').evaluateAll(ws => ws.map(w => w.dataset.f)), f).toEqual(KEYS);
      expect(await page.locator('[data-f]').evaluateAll(ws => ws.filter(w => w.dataset.req === '1').map(w => w.dataset.f))).toEqual(REQUIRED);
      expect(await page.locator('[data-f]').evaluateAll(ws => ws.filter(w => w.dataset.req !== '1').map(w => w.dataset.f))).toEqual(OPTIONAL);
      for (const k of OPTIONAL) await expect(page.locator(`[data-f=${k}] .req`)).toHaveCount(0);
      for (const k of REQUIRED) await expect(page.locator(`[data-f=${k}] .req`)).toHaveCount(1);
      expect(await page.locator('form.app input[type=file]').count(), 'attachments not in V1').toBe(0);
      expect(await page.locator('form.app input[type=checkbox]').count(), 'one checkbox: consent (no marketing opt-in)').toBe(1);
      expect(await page.locator('form.app').textContent()).not.toMatch(/القدرة الاستثمارية|investment capacity|مرفقات|attachment/i);
      await expect(page.locator('#message')).toHaveAttribute('maxlength', '2000');
      expect((await page.locator('#years option').allTextContents()).slice(1)).toHaveLength(6);
      expect((await page.locator('label.consent').textContent()).replace('*', '').trim()).toBe(CONSENT[l]);
      await expect(page.locator('#h-consent')).toContainText('PENDING OWNER APPROVAL (PF-03)');
      await expect(page.locator('#disclaimer')).toContainText(DISCLAIMER[l]);
      await expect(page.locator('#disclaimer')).toContainText(LEGAL);
      await expect(page.locator('#h-interest')).toContainText('PF-06');
      const textNoAuto = await page.locator('form.app input[type=text], form.app input[type=tel], form.app input[type=email], form.app input[type=url], form.app textarea').evaluateAll(es => es.filter(e => e.getAttribute('dir') !== 'auto').map(e => e.id));
      expect(textNoAuto).toEqual([]);
    }
    await page.goto(`${F}${l}-form-b.html`);
    expect(JSON.parse(await page.locator('form.app').getAttribute('data-steps'))).toEqual(STEP_NAMES[l]);
    expect(await page.locator('.bars li').count()).toBe(5);
    expect(await page.locator('.step').evaluateAll(ss => ss.map(s => [...s.querySelectorAll('[data-f]')].map(w => w.dataset.f)))).toEqual([
      ['name', 'phone', 'email'], ['country', 'city', 'market'], ['years', 'expnote', 'owns', 'company', 'website'], ['interest', 'location', 'message'], ['consent']]);
  });

  for (const l of LANGS) test(`${l} success: thank-you, SAMPLE application number, review message, no promises, no PII @franchise @structure`, async ({ page }, ti) => {
    onlyOn(ti, 'm390');
    await page.goto(`${F}${l}-success.html`);
    await expect(page.locator('h1')).toHaveText(l === 'ar' ? 'شكرًا لاهتمامك بالشراكة مع SHELTER COFFEE' : 'Thank you for your interest in partnering with SHELTER COFFEE');
    await expect(page.locator('.appno')).toHaveText('FR-2026-00125');
    await expect(page.locator('[role=status] .sample')).toContainText('SAMPLE');
    await expect(page.locator('main')).toContainText(l === 'ar' ? 'سيخضع طلبك للمراجعة' : 'will be reviewed');
    const t = await page.locator('[role=status]').textContent();
    expect(t).not.toMatch(/خلال|within|اجتماع|meeting|مقبول|accepted|approved|سيتم قبول|حق الامتياز/i);
    expect(/@|\+?\d{9,}/.test(await page.locator('main').textContent()), 'no PII').toBe(false);
    expect(page.url()).not.toContain('?');
  });
});

test.describe('franchise · owner dashboard contract (docs/franchise/04)', () => {
  for (const kind of ['d', 'm']) {
    test(`${kind === 'd' ? 'desktop' : 'mobile'}: nav, overview, list, filters, quick view, application, meetings, settings @franchise @structure`, async ({ page }, ti) => {
      onlyOn(ti, kind === 'd' ? 'd1440' : 'm390');
      const go = async f => page.goto(`${F}${kind}-${f}.html`);
      await go('overview');
      expect((await page.locator('nav[aria-label="أقسام الشراكات"] a').allTextContents()).map(t => t.replace(/\d+.*$/, '').trim())).toEqual(D_NAV);
      const kpis = page.locator('a.kpi');
      expect(await kpis.count()).toBe(4); // operational cards only
      expect(await page.locator('canvas, [role=img], [class*=chart]').count(), 'no charts').toBe(0);
      expect(await page.locator('main').textContent()).not.toMatch(/[%٪]/);
      await go('list');
      if (kind === 'd') {
        const heads = (await page.locator('.ds-table thead th').allTextContents()).map(t => t.trim()).filter(t => t && t !== 'عرض سريع');
        expect(heads).toEqual(COLS);
        expect(await page.locator('.pager a[aria-label^="صفحة"]').count()).toBeGreaterThan(1);
      } else {
        expect(await page.locator('table').count()).toBe(0);
        expect(await page.locator('.acard').count()).toBe(12);
      }
      const q = page.getByLabel('بحث', { exact: true });
      await expect(q).toHaveAttribute('type', 'search');
      for (const s of SEARCH_BY) await expect(q).toHaveAttribute('placeholder', new RegExp(s));
      expect((await page.locator('nav[aria-label="حسب المرحلة"] a').allTextContents()).map(t => t.trim())).toEqual(['الكل', ...STAGES]);
      await expect(page.locator('#saved .ds-chip').first()).toBeVisible();
      await expect(page.locator('.pager')).toContainText('السابق');
      await expect(page.locator('.pager')).toContainText('التالي');
      await expect(page.getByLabel('انتقل إلى صفحة')).toBeVisible();
      expect(await page.locator('#ps option').allTextContents()).toEqual(['25', '50', '100']);
      await go('list-filters');
      const dlg = page.locator('[role=dialog]');
      const fl = await dlg.locator('.dlg-b > .ds-field:not(.save) > label, .dlg-b > fieldset.ds-field:not(.save) > legend').allTextContents();
      expect(fl.map(t => t.trim())).toEqual(FILTERS);
      await expect(dlg).toContainText('حفظ الفلتر');
      await go('quickview');
      for (const t of ['الدولة', 'المدينة', 'السوق المقترح', 'المرحلة', 'الهاتف', 'البريد']) await expect(page.locator('[role=dialog]')).toContainText(t);
      expect(await page.locator('#qv-st option').allTextContents()).toEqual(STAGES);
      await expect(page.locator('[role=dialog]').getByRole('link', { name: 'فتح الطلب الكامل' })).toBeVisible();
      await go('application');
      const secs = await page.locator('section.dpanel > h2').allTextContents();
      for (const s of APP_SECTIONS) expect(secs.some(h => h.includes(s)), s).toBe(true);
      expect(await page.locator('#s-notes .notes li').count()).toBeGreaterThanOrEqual(2);
      for (const by of await page.locator('#s-notes .by').allTextContents()) expect(by).toMatch(/المالك \(Owner\).*\d{4}-\d{2}-\d{2} \d{2}:\d{2}/);
      for (const l of ['تاريخ الاجتماع', 'وقت الاجتماع', 'المكان أو القناة', 'ملاحظات داخلية', 'حالة الاجتماع']) await expect(page.locator('#s-meet').getByLabel(l)).toBeVisible();
      await expect(page.locator('#s-files')).toContainText('disabled in V1');
      await expect(page.locator('#s-files button')).toBeDisabled();
      await expect(page.locator('main')).toContainText('طلبات سابقة محتملة (2) — بلا دمج');
      await expect(page.locator('#s-prev')).toContainText('لا دمج تلقائي');
      if (kind === 'd') expect((await page.locator('#s-audit thead th').allTextContents()).map(t => t.trim())).toEqual(AUDIT_COLS);
      else for (const c of AUDIT_COLS) await expect(page.locator('#s-audit')).toContainText(c);
      expect(await page.locator('#app-st option').allTextContents()).toEqual(STAGES);
      expect(await page.locator('input[type=range], input[type=number], meter, progress').count(), 'no scoring controls').toBe(0);
      expect(await page.locator('main').textContent()).not.toMatch(/\bAI\b|ذكاء اصطناعي|score|scoring|نقاط التقييم|قبول تلقائي|رفض تلقائي/i);
      await go('meetings');
      for (const t of ['التاريخ', 'الوقت', 'المكان أو القناة', 'حالة الاجتماع']) await expect(page.locator('main')).toContainText(t);
      await go('archived');
      await expect(page.getByRole('button', { name: 'استعادة' }).first()).toBeVisible();
      expect(await page.locator('main').textContent()).not.toMatch(/حذف نهائي/);
      await go('settings');
      const codes = await page.locator('main code').allTextContents();
      expect(codes).toEqual(CODES); // configurable pipeline table (TD-FR-01)
      for (const t of ['نص الموافقة v1', 'PENDING OWNER APPROVAL (PF-03)', 'الـDisclaimer v1', LEGAL, 'إضافة مرحلة']) await expect(page.locator('main')).toContainText(t);
      const all = await page.locator('body').textContent();
      expect(all, 'V1 is owner only: no user / role management').not.toMatch(/المستخدمين|إدارة المستخدمين|الأدوار|Roles|Permissions|إضافة مستخدم/);
    });
  }
});

// ---- A/B measurement (owner delegated single page vs short multi-step to testing — M29 §33: "اختر الأقل Friction")
const VPS = [[360, 800], [390, 844], [430, 932]];
const radio = (l, k, o) => p => group(p, GROUPS_Q[l][k]).getByLabel(o, { exact: true });
const FILL = l => [ // [B step, locator, action] — required fields only, same order in A and B
  [1, p => p.getByLabel(LABELS[l].name), x => x.fill(l === 'ar' ? 'متقدم تجريبي' : 'Sample Applicant')],
  [1, p => p.getByLabel(LABELS[l].phone), x => x.fill('+962700000001')],
  [1, p => p.getByLabel(LABELS[l].email), x => x.fill('applicant@example.com')],
  [2, p => p.getByLabel(LABELS[l].country), x => x.selectOption({ index: 1 })],
  [2, p => p.getByLabel(LABELS[l].city), x => x.fill(l === 'ar' ? 'مدينة تجريبية' : 'Sample city')],
  [2, p => p.getByLabel(LABELS[l].market), x => x.fill(l === 'ar' ? 'سوق تجريبي' : 'Sample market')],
  [3, p => p.getByLabel(LABELS[l].years), x => x.selectOption({ index: 4 })],
  [3, radio(l, 'owns', OPTS[l].owns[0]), x => x.check()],
  [4, p => p.getByLabel(LABELS[l].interest), x => x.fill(l === 'ar' ? 'نص تجريبي' : 'Sample text')],
  [4, radio(l, 'location', OPTS[l].location[1]), x => x.check()],
  [4, p => p.getByLabel(LABELS[l].message), x => x.fill(l === 'ar' ? 'رسالة تجريبية قصيرة.' : 'A short sample introduction.')],
  [5, p => p.getByLabel(CONSENT[l]), x => x.check()],
];

async function run(page, l, variant, { skip = -1 } = {}) {
  let n = 0, scrolled = 0; const stepScreens = [];
  const screens = () => page.evaluate(() => +(document.documentElement.scrollHeight / innerHeight).toFixed(2));
  const reach = async loc => { // the minimal scroll a person needs to bring the control into view (16px margin)
    const y0 = await page.evaluate(() => scrollY);
    await loc.evaluate(e => { const r = e.getBoundingClientRect(), m = 16; const dy = r.bottom > innerHeight - m ? r.bottom - (innerHeight - m) : r.top < m ? r.top - m : 0; if (dy) scrollBy(0, dy); });
    scrolled += Math.abs((await page.evaluate(() => scrollY)) - y0);
  };
  const next = async () => { const b = page.locator('.step:not([hidden])').getByRole('button', { name: NEXT[l] }); await reach(b); await b.click(); n++; };
  let step = 1; stepScreens.push(await screens());
  for (const [i, [s, loc, act]] of FILL(l).entries()) {
    if (variant === 'B' && s !== step) { await next(); step = s; stepScreens.push(await screens()); if (await page.locator('.esum').count()) return { stoppedAtStep: step - 1, n, scrolled }; }
    if (i === skip) continue;
    const x = loc(page); await reach(x);
    const y0 = await page.evaluate(() => scrollY); await act(x); n++;
    scrolled += Math.abs((await page.evaluate(() => scrollY)) - y0); // any scroll the action itself caused counts as user effort too
  }
  const submit = page.locator('form.app button[type=submit]:visible').last();
  const filledScreens = await screens();
  await reach(submit); await submit.click(); n++;
  return { n, scrolled, stepScreens, filledScreens };
}

async function errorView(page) {
  return page.evaluate(() => {
    const s = document.querySelector('.esum'); if (!s) return null;
    const inView = e => { const r = e.getBoundingClientRect(); return r.top >= 0 && r.top < innerHeight && r.bottom > 0; };
    const err = document.querySelector('.err');
    return { summaryVisible: inView(s.querySelector('h2,h3')) && inView(s.querySelector('li')), summaryFocused: document.activeElement === s,
      errorsListed: s.querySelectorAll('li').length, summaryScreens: +(s.getBoundingClientRect().height / innerHeight).toFixed(2), firstInlineErrorVisible: !!err && inView(err) };
  });
}

test.describe('franchise · A/B measurement', () => {
  test('single page (A) vs 5 short steps (B) at 360/390/430, AR + EN → evidence JSON @franchise @measure', async ({ browser }, ti) => {
    onlyOn(ti, 'm390');
    test.skip(ti.project.name.split('-')[0] !== 'chromium', 'measured once, in Chromium');
    test.setTimeout(240_000);
    const out = { spec: 'M29 §33 — single structured form vs short multi-step (About you → Market → Experience → Opportunity → Review & submit); owner: choose the lower friction',
      method: ['Same fields (docs/franchise/03: 11 required + 3 optional + consent), same order, same intro block, AR and EN pages; happy path fills the 11 required fields + consent and skips the optional ones.',
        'interactionsToSubmit = Playwright actions on the happy path (fill/select/check = 1 each) + step buttons + submit.',
        'userScrollScreens = (sum of the minimal scrolls needed to bring each control into view (16px margin) + any scroll the fill/select/check itself caused) ÷ viewport height; the page’s own programmatic scroll (B step change, error summary focus) is not counted.',
        'pageScreens = document height ÷ viewport height (A: empty and filled; B: each step on entry).',
        'effort = interactionsToSubmit + userScrollScreens (lower = less friction). Error visibility: empty submit (A) / empty step 1 (B), and a realistic miss (only City left empty). "Visible" = in the viewport with no extra scrolling.'],
      results: {} };
    for (const l of LANGS) {
      out.results[l] = {};
      for (const [w, h] of VPS) {
        const ctx = await browser.newContext({ viewport: { width: w, height: h }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
        const page = await ctx.newPage(); const res = {};
        for (const v of ['A', 'B']) {
          const file = `${F}${l}-form-${v.toLowerCase()}.html`;
          await page.goto(file);
          const emptyScreens = +(await page.evaluate(() => document.documentElement.scrollHeight / innerHeight)).toFixed(2);
          const happy = await run(page, l, v);
          await expect(page).toHaveURL(new RegExp(`${l}-success\\.html$`));
          await page.goto(file);
          const b = page.locator('.step:not([hidden]) [data-nav=next], form.app[data-variant=A] button[type=submit]').first();
          const y0 = await page.evaluate(() => scrollY); await b.scrollIntoViewIfNeeded(); const scrollToFirstButton = +(((await page.evaluate(() => scrollY)) - y0) / h).toFixed(2);
          await b.click();
          const emptyErr = await errorView(page);
          await page.goto(file);
          const miss = await run(page, l, v, { skip: 4 }); // leave only City empty
          const missErr = await errorView(page);
          const scroll = +(happy.scrolled / h).toFixed(2);
          res[v] = {
            pageScreensEmpty: emptyScreens, ...(v === 'A' ? { pageScreensFilled: happy.filledScreens } : { stepScreens: happy.stepScreens, maxStepScreens: Math.max(...happy.stepScreens) }),
            interactionsToSubmit: happy.n, userScrollScreens: scroll, effort: +(happy.n + scroll).toFixed(2),
            emptySubmit: { scrollBeforeFirstFeedbackScreens: scrollToFirstButton, ...emptyErr },
            realisticMiss: { caughtAtStep: v === 'B' ? miss.stoppedAtStep : 'submit', ...missErr },
          };
        }
        out.results[l][`${w}x${h}`] = res; await ctx.close();
      }
    }
    const rows = Object.entries(out.results).flatMap(([l, r]) => Object.entries(r).map(([vp, x]) => [`${l} ${vp}`, x]));
    out.summary = {
      interactions: { A: rows[0][1].A.interactionsToSubmit, B: rows[0][1].B.interactionsToSubmit },
      userScrollScreens: Object.fromEntries(rows.map(([k, x]) => [k, { A: x.A.userScrollScreens, B: x.B.userScrollScreens }])),
      effort: Object.fromEntries(rows.map(([k, x]) => [k, { A: x.A.effort, B: x.B.effort }])),
      firstErrorVisibleWithoutScroll: Object.fromEntries(rows.map(([k, x]) => [k, { A: x.A.emptySubmit.summaryVisible && x.A.realisticMiss.summaryVisible, B: x.B.emptySubmit.summaryVisible && x.B.realisticMiss.summaryVisible }])),
      lowerFriction: Object.fromEntries(rows.map(([k, x]) => [k, x.A.effort < x.B.effort ? 'A' : x.B.effort < x.A.effort ? 'B' : 'tie'])),
    };
    await mkdir(new URL('../../../docs/franchise/wireframes/evidence/', import.meta.url), { recursive: true });
    await writeFile(new URL('../../../docs/franchise/wireframes/evidence/form-variant-measure.json', import.meta.url), JSON.stringify(out, null, 1) + '\n');
    await ti.attach('form-variant-measure.json', { body: JSON.stringify(out, null, 1), contentType: 'application/json' });
    for (const [, r] of rows) for (const v of ['A', 'B']) { expect(r[v].emptySubmit.summaryFocused).toBe(true); expect(r[v].realisticMiss.errorsListed).toBe(1); }
  });
});
